begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.id(n integer) returns uuid language sql immutable as $$select ('4d100000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table console_state(k text primary key,v jsonb);
grant all on console_state to authenticated;
create function pg_temp.account_id() returns uuid language sql as $$select (v->>'account_id')::uuid from console_state where k='tenant'$$;
create function pg_temp.intent_id() returns uuid language sql as $$select (v->>'intent_id')::uuid from console_state where k='intent'$$;
-- Use the existing minimal Auth fixture contract; production GoTrue eligibility
-- fields are additionally enforced when present by the completion RPC.
insert into auth.users(id,aud,role,email,confirmed_at) values
 (pg_temp.id(1),'authenticated','authenticated','console-operator@example.invalid',now()),
 (pg_temp.id(2),'authenticated','authenticated','console-admin@example.invalid',null),
 (pg_temp.id(3),'authenticated','authenticated','console-sandbox@example.invalid',now());
insert into public.persons(id,auth_user_id,display_name) values
 (pg_temp.id(11),pg_temp.id(1),'Fictional platform operator'),(pg_temp.id(13),pg_temp.id(3),'Fictional sandbox operator'),(pg_temp.id(14),null,'Fictional cashier');
insert into pikas_private.platform_memberships(person_id,role_code) values (pg_temp.id(11),'platform_admin'),(pg_temp.id(11),'platform_sandbox_operator'),(pg_temp.id(13),'platform_sandbox_operator');
insert into public.accounts(id,code,name,tenant_kind) values(pg_temp.id(21),'4D1-SANDBOX','Fictional sandbox','sandbox');
insert into public.schools(id,account_id,code,name) values(pg_temp.id(22),pg_temp.id(21),'S','Sandbox school');
insert into public.school_locations(id,account_id,school_id,code,name) values(pg_temp.id(23),pg_temp.id(21),pg_temp.id(22),'L','Sandbox location');
insert into public.cafeterias(id,account_id,school_id,school_location_id,code,name) values(pg_temp.id(24),pg_temp.id(21),pg_temp.id(22),pg_temp.id(23),'C','Sandbox cafeteria');
insert into public.cafeteria_memberships(id,account_id,school_id,cafeteria_id,person_id,role_code) values(pg_temp.id(25),pg_temp.id(21),pg_temp.id(22),pg_temp.id(24),pg_temp.id(14),'pos_cashier');
insert into pikas_private.sandbox_pov_personas(account_id,school_id,cafeteria_id,pov_code,person_id,cafeteria_membership_id) values(pg_temp.id(21),pg_temp.id(22),pg_temp.id(24),'cashier',pg_temp.id(14),pg_temp.id(25));
select ok(has_function_privilege('authenticated','public.platform_list_customers(text,text,text,uuid,integer)','execute') and not has_function_privilege('anon','public.platform_list_customers(text,text,text,uuid,integer)','execute'),'Customer listing is authenticated-only');
select ok(not has_function_privilege('service_role','public.platform_get_customer_overview(uuid)','execute') and not has_function_privilege('anon','public.platform_complete_initial_customer_admin(uuid,uuid,text)','execute'),'New contracts expose no anonymous/service-role access');
select is((select count(*) from pikas_private.platform_role_capabilities where role_code='platform_admin'),5::bigint,'Original platform capabilities are unchanged');
select set_config('request.jwt.claim.sub','',true);
set local role authenticated;
select throws_ok($$select public.platform_list_customers()$$,'42501',null,'Authenticated role without identity is denied');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
set local role authenticated;
select public.platform_enter_sandbox_pov(pg_temp.id(30),pg_temp.id(21),pg_temp.id(24),'cashier');
select is(public.get_pos_access_context()->'actor'->>'person_id',pg_temp.id(14)::text,'Fixture has real active delegated cashier POV');
select throws_ok($$select public.platform_list_customers()$$,'42501',null,'Active cashier POV cannot supply platform customer-read authority');
select throws_ok($$select public.platform_get_customer_overview(pg_temp.id(21))$$,'42501',null,'Active cashier POV cannot supply detail authority');
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(31),pg_temp.id(32),'Admin')$$,'42501',null,'Sandbox-only operator cannot grant customer admin');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002001',true);
set local role authenticated;
select throws_ok($$select public.platform_list_customers()$$,'42501',null,'Ordinary tenant identity cannot list platform customers');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
set local role authenticated;
select public.platform_enter_sandbox_pov(pg_temp.id(33),pg_temp.id(21),pg_temp.id(24),'cashier');
insert into console_state values('tenant',public.platform_provision_tenant(pg_temp.id(40),'4D1-CUSTOMER','Fictional customer','S','Fictional school','America/Santo_Domingo','L','Fictional location','C','Fictional cafeteria'));
select is(jsonb_array_length(public.platform_list_customers('4D1-CUSTOMER')->'customers'),1,'Search resolves provisioned customer');
select is(public.platform_list_customers('4D1-CUSTOMER')->'customers'->0->>'tenant_kind','customer','Existing atomic provisioning creates customer kind even during POV');
select is(public.platform_list_customers('4D1-SANDBOX',null,'sandbox')->'customers'->0->>'tenant_kind','sandbox','Sandbox kind is distinct and unchanged');
select is(jsonb_array_length(public.platform_list_customers('not-present')->'customers'),0,'Empty list is an intentional successful response');
select is(jsonb_array_length(public.platform_list_customers('4D1',null,null,null,1)->'customers'),1,'List page is bounded');
select ok(public.platform_list_customers('4D1',null,null,null,1)->>'next_cursor' is not null,'Bounded list exposes continuation');
select is(jsonb_array_length(public.platform_list_customers('4D1',null,null,(public.platform_list_customers('4D1',null,null,null,1)->>'next_cursor')::uuid,1)->'customers'),1,'Continuation returns the next customer');
select throws_ok($$select public.platform_list_customers('',null,'invalid')$$,'22023','invalid_customer_filter','Invalid kind fails closed');
select throws_ok($$select public.platform_list_customers('',null,null,null,101)$$,'22023','invalid_customer_filter','Unbounded page rejected');
select is(public.platform_list_customers('4D1-CUSTOMER')->'customers'->0->>'cafeteria_count','1','Hierarchy summary is authoritative');
select is(public.platform_get_customer_overview(pg_temp.account_id())->'schools'->0->'locations'->0->'cafeterias'->0->>'name','Fictional cafeteria','Overview reuses full hierarchy');
select throws_ok($$select public.platform_get_customer_overview(pg_temp.id(99))$$,'P0002','tenant_not_found','Missing customer does not leak other tenant');
insert into console_state values('intent',public.platform_prepare_customer_admin(pg_temp.id(41),pg_temp.account_id(),'account',null,null,'account_admin','console-admin@example.invalid',now()+interval '7 days'));
select is(public.platform_get_customer_overview(pg_temp.account_id())->'administrator_intents'->0->>'status','pending','Admin prepare is honestly pending');
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(42),pg_temp.intent_id(),'Fictional admin')$$,'23514','confirmed_identity_pending','Unconfirmed email never confers authority');
reset role;
select is((select count(*) from public.persons where auth_user_id=pg_temp.id(2)),0::bigint,'Unconfirmed identity does not create Person');
select is((select count(*) from public.account_memberships where account_id=pg_temp.account_id()),0::bigint,'Unconfirmed identity does not create membership');
select is((select actor_person_id from pikas_private.platform_requests where request_id=pg_temp.id(40)),pg_temp.id(11),'Real operator remains provisioning actor during delegated POV');
select ok(exists(select 1 from pikas_private.platform_audit_events where request_id=pg_temp.id(40) and actor_person_id=pg_temp.id(11) and actor_auth_user_id=pg_temp.id(1) and action='tenant_provisioned'),'Provisioning audit attributes real operator');
update auth.users set confirmed_at=now() where id=pg_temp.id(2);
set local role authenticated;
insert into console_state values('grant',public.platform_complete_initial_customer_admin(pg_temp.id(42),pg_temp.intent_id(),'Fictional admin'));
select is((select v->>'status' from console_state where k='grant'),'granted','Confirmed intended identity is linked and granted atomically');
select is(public.platform_complete_initial_customer_admin(pg_temp.id(42),pg_temp.intent_id(),'Fictional admin'),(select v from console_state where k='grant'),'Exact retry safely replays committed result');
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(42),pg_temp.intent_id(),'Changed name')$$,'23505',null,'Changed payload cannot reuse request identity');
select is(public.platform_get_customer_overview(pg_temp.account_id())->'administrator_intents'->0->>'status','granted','Detail shows committed admin state');
select is(public.platform_get_customer_overview(pg_temp.account_id())->'administrators'->0->>'display_name','Fictional admin','Detail reflects actual administrator authority');
reset role;
select is((select count(*) from public.account_memberships where account_id=pg_temp.account_id() and role_code='account_admin' and status='active'),1::bigint,'Exactly one intended account admin membership');
select is((select count(*) from public.account_memberships where account_id=pg_temp.account_id() and person_id=pg_temp.id(11)),0::bigint,'Operator is not made a customer member');
select is((select count(*) from pikas_private.platform_memberships where person_id=(select (v->>'person_id')::uuid from console_state where k='grant')),0::bigint,'Customer administrator receives no platform authority');
select is((select count(*) from pikas_private.platform_audit_events where target_intent_id=pg_temp.intent_id() and action in ('customer_admin_identity_linked','customer_admin_membership_granted') and actor_person_id=pg_temp.id(11) and actor_auth_user_id=pg_temp.id(1)),2::bigint,'Existing link/grant audit evidence is attributable and replay emits no duplicates');
select is((select count(*) from public.persons where auth_user_id=pg_temp.id(2)),1::bigint,'Replay does not duplicate Person');
select is((select count(*) from public.purchases where account_id=pg_temp.account_id()),0::bigint,'Customer provisioning creates no sales');
select throws_ok($$update public.accounts set tenant_kind='sandbox' where id=pg_temp.account_id()$$,'23514','account_tenant_kind_is_immutable','Tenant kind protection remains strict');
set local role authenticated;
insert into console_state values('second',public.platform_prepare_customer_admin(pg_temp.id(43),pg_temp.account_id(),'account',null,null,'account_admin','console-admin@example.invalid',now()+interval '7 days'));
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(44),(select (v->>'intent_id')::uuid from console_state where k='second'),'Another admin')$$,'23505','initial_admin_already_exists','Initial-admin wrapper does not become general staff provisioning');
insert into console_state values('sandbox-intent',public.platform_prepare_customer_admin(pg_temp.id(45),pg_temp.id(21),'account',null,null,'account_admin','console-admin@example.invalid',now()+interval '7 days'));
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(46),(select (v->>'intent_id')::uuid from console_state where k='sandbox-intent'),'Admin')$$,'42501','active_customer_required','Initial customer admin cannot be granted inside sandbox');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
set local role authenticated;
insert into console_state values('guard-tenant',public.platform_provision_tenant(pg_temp.id(50),'4D1-GUARD','Guard customer','S','Guard school','America/Santo_Domingo','L','Guard location','C','Guard cafeteria'));
insert into console_state values('self-intent',public.platform_prepare_customer_admin(pg_temp.id(51),(select (v->>'account_id')::uuid from console_state where k='guard-tenant'),'account',null,null,'account_admin','console-operator@example.invalid',now()+interval '7 days'));
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(52),(select (v->>'intent_id')::uuid from console_state where k='self-intent'),'Operator')$$,'42501','customer_identity_required','Operator cannot provision themselves as initial customer admin');
insert into console_state values('school-intent',public.platform_prepare_customer_admin(pg_temp.id(53),(select (v->>'account_id')::uuid from console_state where k='guard-tenant'),'school',(select (v->>'school_id')::uuid from console_state where k='guard-tenant'),null,'school_admin','console-admin@example.invalid',now()+interval '7 days'));
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(54),(select (v->>'intent_id')::uuid from console_state where k='school-intent'),'Admin')$$,'23514','initial_customer_admin_intent_required','Wrapper cannot broaden initial-admin role or scope');
reset role;
update public.accounts set status='suspended' where id=(select (v->>'account_id')::uuid from console_state where k='guard-tenant');
set local role authenticated;
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(55),(select (v->>'intent_id')::uuid from console_state where k='self-intent'),'Admin')$$,'42501','active_customer_required','Inactive customer is not eligible for completion');
reset role;
select is((select count(*) from public.account_memberships where account_id=(select (v->>'account_id')::uuid from console_state where k='guard-tenant')),0::bigint,'Rejected guard cases leave no partial authority');
update public.accounts set status='active' where id=(select (v->>'account_id')::uuid from console_state where k='guard-tenant');
insert into auth.users(id,aud,role,email,confirmed_at) values(pg_temp.id(63),'authenticated','authenticated','CONSOLE-OPERATOR@example.invalid',now());
set local role authenticated;
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(64),(select (v->>'intent_id')::uuid from console_state where k='self-intent'),'Admin')$$,'23514','confirmed_identity_pending','Ambiguous normalized email fails closed rather than selecting an arbitrary identity');
insert into console_state values('missing-intent',public.platform_prepare_customer_admin(pg_temp.id(65),(select (v->>'account_id')::uuid from console_state where k='guard-tenant'),'account',null,null,'account_admin','not-registered@example.invalid',now()+interval '7 days'));
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(66),(select (v->>'intent_id')::uuid from console_state where k='missing-intent'),'Admin')$$,'23514','confirmed_identity_pending','Missing identity remains pending');
reset role;
select is((select count(*) from auth.users where email='not-registered@example.invalid'),0::bigint,'Completion never creates an Auth identity');
-- An expired request fixture is inserted already expired, without changing immutable intent history.
insert into pikas_private.platform_requests(request_id,operation,request_fingerprint,actor_auth_user_id,actor_person_id,response)
 values(pg_temp.id(60),'expired_test_fixture',repeat('0',64),pg_temp.id(1),pg_temp.id(11),'{}');
insert into pikas_private.platform_customer_admin_intents(id,request_id,account_id,scope_kind,role_code,intended_email_key,created_by_person_id,created_at,expires_at)
 values(pg_temp.id(61),pg_temp.id(60),(select (v->>'account_id')::uuid from console_state where k='guard-tenant'),'account','account_admin','console-admin@example.invalid',pg_temp.id(11),now()-interval '2 hours',now()-interval '1 hour');
set local role authenticated;
select throws_ok($$select public.platform_complete_initial_customer_admin(pg_temp.id(62),pg_temp.id(61),'Admin')$$,'23514','initial_customer_admin_intent_required','Expired request cannot grant authority');
select is((select item->>'status' from jsonb_array_elements(public.platform_get_customer_overview((select (v->>'account_id')::uuid from console_state where k='guard-tenant'))->'administrator_intents') item where item->>'id'=pg_temp.id(61)::text),'expired','Overview renders pending-but-expired intent accurately');
reset role;
select * from finish();
rollback;
