begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.id(n integer) returns uuid language sql immutable as $$select ('4d200000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.a() returns uuid language sql immutable as $$select '00000000-0000-0000-0000-000000000011'::uuid$$;
create function pg_temp.command(n integer,op text,payload jsonb) returns jsonb language sql as $$select public.school_admin_command(pg_temp.a(),pg_temp.id(n),op,payload)$$;
create temp table state(k text primary key,v jsonb);
grant all on state to authenticated;
create function pg_temp.student_id() returns uuid language sql as $$select (v->>'student_id')::uuid from state where k='student'$$;
create function pg_temp.invite_id() returns uuid language sql as $$select (v->>'invitation_id')::uuid from state where k='invite'$$;
create function pg_temp.member_id() returns uuid language sql as $$select (v->>'membership_id')::uuid from state where k='grant'$$;
insert into auth.users(id,aud,role,email,confirmed_at) values
 (pg_temp.id(1),'authenticated','authenticated','school-new@example.invalid',null),
 (pg_temp.id(2),'authenticated','authenticated','school-platform@example.invalid',now()),
 (pg_temp.id(3),'authenticated','authenticated','school-ambiguous@example.invalid',now()),
 (pg_temp.id(4),'authenticated','authenticated','SCHOOL-AMBIGUOUS@example.invalid',now());
insert into public.persons(id,auth_user_id,display_name) values(pg_temp.id(12),pg_temp.id(2),'Synthetic platform operator'),(pg_temp.id(14),null,'Synthetic cashier');
insert into pikas_private.platform_memberships(person_id,role_code) values(pg_temp.id(12),'platform_admin'),(pg_temp.id(12),'platform_sandbox_operator');
insert into public.accounts(id,code,name,tenant_kind) values(pg_temp.id(21),'4D2-SANDBOX','Synthetic sandbox','sandbox');
insert into public.schools(id,account_id,code,name) values(pg_temp.id(22),pg_temp.id(21),'S','Synthetic sandbox school');
insert into public.school_locations(id,account_id,school_id,code,name) values(pg_temp.id(23),pg_temp.id(21),pg_temp.id(22),'L','Synthetic sandbox campus');
insert into public.cafeterias(id,account_id,school_id,school_location_id,code,name) values(pg_temp.id(24),pg_temp.id(21),pg_temp.id(22),pg_temp.id(23),'C','Synthetic sandbox cafeteria');
insert into public.cafeteria_memberships(id,account_id,school_id,cafeteria_id,person_id,role_code) values(pg_temp.id(25),pg_temp.id(21),pg_temp.id(22),pg_temp.id(24),pg_temp.id(14),'pos_cashier');
insert into pikas_private.sandbox_pov_personas(account_id,school_id,cafeteria_id,pov_code,person_id,cafeteria_membership_id) values(pg_temp.id(21),pg_temp.id(22),pg_temp.id(24),'cashier',pg_temp.id(14),pg_temp.id(25));
insert into public.school_memberships(id,account_id,school_id,person_id,role_code,status) values(pg_temp.id(26),'00000000-0000-0000-0000-000000000001',pg_temp.a(),pg_temp.id(12),'school_admin','suspended');
insert into public.persons(id,display_name) values(pg_temp.id(15),'Synthetic foreign student');
insert into public.students(id,account_id,school_id,person_id,student_code,first_name,last_name,display_name) values(pg_temp.id(16),'00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000012',pg_temp.id(15),'FOREIGN','Foreign','Student','Synthetic foreign student');
select ok(has_function_privilege('authenticated','public.get_school_admin_context()','execute') and not has_function_privilege('anon','public.get_school_admin_context()','execute'),'Context is authenticated-only');
select ok(not has_function_privilege('service_role','public.school_admin_command(uuid,uuid,text,jsonb)','execute'),'No service-role execution');
select ok(not has_table_privilege('authenticated','pikas_private.school_admin_requests','select'),'Recovery journal is private');
select is((select count(*) from pikas_private.platform_role_capabilities where role_code='platform_admin'),5::bigint,'Platform authority unchanged');
select set_config('request.jwt.claim.sub','',true);
set local role authenticated;
select is(public.get_school_admin_context(),null::jsonb,'Unauthenticated context provides no scope');
select throws_ok($$select public.school_admin_read(pg_temp.a(),'summary')$$,'42501',null,'Unauthenticated read denied');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
set local role authenticated;
select public.platform_enter_sandbox_pov(pg_temp.id(30),pg_temp.id(21),pg_temp.id(24),'cashier');
select is(public.get_pos_access_context()->'actor'->>'person_id',pg_temp.id(14)::text,'Synthetic operator has valid delegated cashier POV');
select is(public.get_school_admin_context()->>'person_id',pg_temp.id(12)::text,'School context never substitutes the POV Person');
select is(jsonb_array_length(public.get_school_admin_context()->'schools'),0,'Platform-only active POV gains no tenant scopes');
select throws_ok($$select pg_temp.command(101,'admin_prepare','{"email":"any@example.invalid"}')$$,'42501',null,'Platform-only user cannot prepare tenant authority');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002002',true);
set local role authenticated;
select is(jsonb_array_length(public.get_school_admin_context()->'schools'),1,'School admin resolves exactly their school');
select is(public.get_school_admin_context()->>'person_id','00000000-0000-0000-0000-000000001002','Real authenticated Person remains actor');
select throws_ok($$select public.school_admin_read('00000000-0000-0000-0000-000000000012','students')$$,'42501',null,'Sibling school read denied');
select throws_ok($$select public.school_admin_read('00000000-0000-0000-0000-000000000021','students')$$,'42501',null,'Other account read denied');
select throws_ok($$select public.school_admin_read(pg_temp.id(22),'summary')$$,'42501',null,'Sandbox does not supply customer authority');
select throws_ok($$select public.school_admin_read(pg_temp.a(),null)$$,'22023',null,'Null section rejected');
select throws_ok($$select public.school_admin_read(pg_temp.a(),'students','', '', null,101)$$,'22023',null,'Read limits enforced');
select is(public.school_admin_read(pg_temp.a(),'students','impossible-name')->'rows','[]'::jsonb,'Search is authoritative');
select throws_ok($$select pg_temp.command(102,'student_create','{"actor_id":"4d200000-0000-4000-8000-000000000001"}')$$,'22023',null,'Client actor authority rejected');
select throws_ok($$select pg_temp.command(103,'student_status',jsonb_build_object('student_id',pg_temp.id(16),'status','suspended'))$$,'42501',null,'Cross-school student mutation denied');
select throws_ok($$select pg_temp.command(104,'student_create','{"first_name":"Test","last_name":"Student","student_code":"BAD","starts_on":"2026-01-01","location_id":"00000000-0000-0000-0000-000000000212"}')$$,'42501',null,'Cross-school campus denied');
insert into state values('student',pg_temp.command(110,'student_create','{"first_name":"Fictional","last_name":"Student","student_code":"4D2-001","starts_on":"2026-01-01","location_id":"00000000-0000-0000-0000-000000000211","grade":"3","class":null,"homeroom":null}'));
select is(pg_temp.command(110,'student_create','{"first_name":"Fictional","last_name":"Student","student_code":"4D2-001","starts_on":"2026-01-01","location_id":"00000000-0000-0000-0000-000000000211","grade":"3","class":null,"homeroom":null}'),(select v from state where k='student'),'Create exact replay returns original result');
select throws_ok($$select pg_temp.command(110,'student_create','{"first_name":"Changed"}')$$,'23505',null,'Changed retry payload rejected');
select is(public.school_admin_read(pg_temp.a(),'students','4D2-001')->'rows'->0->'enrollment'->>'grade','3','Student projection includes real placement');
select lives_ok($$select pg_temp.command(111,'student_update',jsonb_build_object('student_id',pg_temp.student_id(),'first_name','Updated','last_name','Student','student_code','4D2-001'))$$,'Supported information updates');
select lives_ok($$select pg_temp.command(112,'student_transfer',jsonb_build_object('student_id',pg_temp.student_id(),'starts_on','2026-02-01','location_id','00000000-0000-0000-0000-000000000213','grade','4','class',null,'homeroom',null))$$,'Campus transfer reuses production RPC');
select is(public.school_admin_read(pg_temp.a(),'students','4D2-001')->'rows'->0->'enrollment'->>'grade','4','Transfer projection authoritative');
select lives_ok($$select pg_temp.command(113,'student_status',jsonb_build_object('student_id',pg_temp.student_id(),'status','suspended'))$$,'Student suspension supported');
select lives_ok($$select pg_temp.command(114,'student_status',jsonb_build_object('student_id',pg_temp.student_id(),'status','active'))$$,'Student activation supported');
select throws_ok($$select pg_temp.command(115,'sharing_set','{"cafeteria_id":"00000000-0000-0000-0000-000000000112","status":"active","categories":["basic_identification"]}')$$,'42501',null,'Sharing cannot cross school');
select lives_ok($$select pg_temp.command(116,'sharing_set','{"cafeteria_id":"00000000-0000-0000-0000-000000000113","status":"active","categories":["basic_identification","placement"]}')$$,'Scoped sharing reuses production RPC');
select lives_ok($$select pg_temp.command(117,'customer_set',jsonb_build_object('cafeteria_id','00000000-0000-0000-0000-000000000113','student_id',pg_temp.student_id(),'enabled',true))$$,'Eligible enrolled student can be shared');
select lives_ok($$select pg_temp.command(118,'customer_set',jsonb_build_object('cafeteria_id','00000000-0000-0000-0000-000000000113','student_id',pg_temp.student_id(),'enabled',false))$$,'Scoped eligibility can be deactivated');
select lives_ok($$select pg_temp.command(119,'customer_set',jsonb_build_object('cafeteria_id','00000000-0000-0000-0000-000000000113','student_id',pg_temp.student_id(),'enabled',true))$$,'Eligible relation can be re-enabled without duplication');
select lives_ok($$select pg_temp.command(120,'student_withdraw',jsonb_build_object('student_id',pg_temp.student_id(),'ends_on','2026-03-01'))$$,'Enrollment withdrawal supported');
select throws_ok($$select pg_temp.command(121,'customer_set',jsonb_build_object('cafeteria_id','00000000-0000-0000-0000-000000000113','student_id',pg_temp.student_id(),'enabled',true))$$,'23514',null,'Reactivation fails without current enrollment');
select lives_ok($$select pg_temp.command(122,'student_enroll',jsonb_build_object('student_id',pg_temp.student_id(),'starts_on','2026-04-01','location_id','00000000-0000-0000-0000-000000000211','grade','4','class',null,'homeroom',null))$$,'Student can be enrolled again');
insert into state values('invite',pg_temp.command(130,'admin_prepare','{"email":"school-new@example.invalid"}'));
select is((select v->>'status' from state where k='invite'),'pending','Prepare does not grant access or claim delivery');
select is(pg_temp.command(131,'admin_prepare','{"email":"school-new@example.invalid"}')->>'invitation_id',pg_temp.invite_id()::text,'Different key reuses live pending email intention');
select throws_ok($$select pg_temp.command(132,'admin_complete',jsonb_build_object('invitation_id',pg_temp.invite_id(),'display_name','New admin'))$$,'23514','confirmed_identity_pending','Unconfirmed identity cannot receive membership');
select throws_ok($$select pg_temp.command(133,'admin_complete',jsonb_build_object('invitation_id',pg_temp.invite_id(),'display_name','New admin','auth_id',pg_temp.id(2)))$$,'22023',null,'Browser cannot select arbitrary Auth identity');
reset role;
select is((select count(*) from public.persons where auth_user_id=pg_temp.id(1)),0::bigint,'Failed onboarding creates no Person');
update auth.users set confirmed_at=now() where id=pg_temp.id(1);
set local role authenticated;
insert into state values('grant',pg_temp.command(132,'admin_complete',jsonb_build_object('invitation_id',pg_temp.invite_id(),'display_name','New admin')));
select is(pg_temp.command(132,'admin_complete',jsonb_build_object('invitation_id',pg_temp.invite_id(),'display_name','New admin')),(select v from state where k='grant'),'Admin completion exact replay idempotent');
select throws_ok($$select pg_temp.command(134,'admin_complete',jsonb_build_object('invitation_id',pg_temp.invite_id(),'display_name','New admin'))$$,'23514',null,'New key cannot recomplete accepted invitation');
select lives_ok($$select pg_temp.command(135,'admin_status',jsonb_build_object('membership_id',pg_temp.member_id(),'status','suspended'))$$,'Intended school membership suspension supported');
reset role;
update auth.users set confirmed_at=null where id=pg_temp.id(1);
set local role authenticated;
select throws_ok($$select pg_temp.command(170,'admin_status',jsonb_build_object('membership_id',pg_temp.member_id(),'status','active'))$$,'23514',null,'Activation cannot reuse an identity that lost confirmation');
reset role;
update auth.users set confirmed_at=now() where id=pg_temp.id(1);
set local role authenticated;
select lives_ok($$select pg_temp.command(136,'admin_status',jsonb_build_object('membership_id',pg_temp.member_id(),'status','active'))$$,'Confirmed school membership activation supported');
select throws_ok($$select pg_temp.command(137,'admin_status','{"membership_id":"00000000-0000-0000-0000-000000003101","status":"suspended"}')$$,'42501',null,'Self suspension denied');
select throws_ok($$select pg_temp.command(138,'admin_status','{"membership_id":"00000000-0000-0000-0000-000000003104","status":"active"}')$$,'42501',null,'Cross-account membership cannot be activated');
select throws_ok($$select pg_temp.command(144,'admin_status',jsonb_build_object('membership_id',pg_temp.id(26),'status','active'))$$,'42501',null,'Tenant administrator cannot reactivate platform identity');
select throws_ok($$select pg_temp.command(139,'admin_status','{"membership_id":"00000000-0000-0000-0000-000000003001","status":"suspended"}')$$,'42501',null,'School path cannot alter account_admin');
insert into state values('platform-invite',pg_temp.command(140,'admin_prepare','{"email":"school-platform@example.invalid"}'));
select throws_ok($$select pg_temp.command(141,'admin_complete',jsonb_build_object('invitation_id',(select v->>'invitation_id' from state where k='platform-invite'),'display_name','Platform'))$$,'42501',null,'Platform identity cannot be made tenant admin');
insert into state values('ambiguous',pg_temp.command(142,'admin_prepare','{"email":"school-ambiguous@example.invalid"}'));
select throws_ok($$select pg_temp.command(143,'admin_complete',jsonb_build_object('invitation_id',(select v->>'invitation_id' from state where k='ambiguous'),'display_name','Ambiguous'))$$,'23514',null,'Ambiguous identity rejected');
select ok(not (public.school_admin_read(pg_temp.a(),'administrators')::text like '%token_hash%') and not(public.school_admin_read(pg_temp.a(),'administrators')::text like '%auth_user_id%'),'Administrator projection excludes Auth IDs and invitation secrets');
select ok(not(public.school_admin_read(pg_temp.a(),'activity')::text like '%metadata%') and not(public.school_admin_read(pg_temp.a(),'activity')::text like '%authenticated_user_id%'),'Activity excludes security metadata');
reset role;
update public.school_locations set status='inactive' where id='00000000-0000-0000-0000-000000000213';
set local role authenticated;
select throws_ok($$select pg_temp.command(171,'sharing_set','{"cafeteria_id":"00000000-0000-0000-0000-000000000113","status":"active","categories":["basic_identification"]}')$$,'42501',null,'Inactive parent campus prevents active sharing');
select throws_ok($$select pg_temp.command(172,'customer_set',jsonb_build_object('cafeteria_id','00000000-0000-0000-0000-000000000113','student_id',pg_temp.student_id(),'enabled',true))$$,'23514',null,'Inactive parent campus prevents customer eligibility reactivation');
reset role;
update public.school_locations set status='active' where id='00000000-0000-0000-0000-000000000213';
select is((select count(*) from public.persons where auth_user_id=pg_temp.id(1)),1::bigint,'Onboarding/replay creates one Person');
select is((select count(*) from public.school_memberships where id=pg_temp.member_id() and school_id=pg_temp.a() and role_code='school_admin'),1::bigint,'Only intended school membership granted');
select is((select count(*) from public.audit_events where request_id=pg_temp.id(132)),1::bigint,'Completion replay emits one audit');
select is((select actor_person_id from public.audit_events where request_id=pg_temp.id(132)),'00000000-0000-0000-0000-000000001002'::uuid,'Real tenant operator is audit actor');
select is((select count(*) from pikas_private.platform_memberships where person_id=(select id from public.persons where auth_user_id=pg_temp.id(1))),0::bigint,'Onboarded administrator receives no platform membership');
select is((select auth_user_id from public.persons where id=(select person_id from public.students where id=pg_temp.student_id())),null::uuid,'Student creation is Auth-less');
select is((select count(*) from public.students where student_code='4D2-001'),1::bigint,'Student replay creates no duplicate');
insert into public.audit_events(actor_role,actor_scope_kind,account_id,school_id,action,target_type,target_id,outcome) values('school_admin','school','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000021','UNRELATED_TENANT_SECRET','students',pg_temp.id(999),'succeeded');
set local role authenticated;
select ok(not(public.school_admin_read(pg_temp.a(),'activity')::text like '%UNRELATED_TENANT_SECRET%'),'Activity cannot leak other tenant');
reset role;
update public.school_memberships set status='suspended' where id='00000000-0000-0000-0000-000000003101';
set local role authenticated;
select is(jsonb_array_length(public.get_school_admin_context()->'schools'),0,'Suspended caller loses workspace');
select throws_ok($$select pg_temp.command(110,'student_create','{}')$$,'42501',null,'Replay rechecks current membership');
reset role;
update public.school_memberships set status='inactive' where id='00000000-0000-0000-0000-000000003101';
set local role authenticated;
select throws_ok($$select public.school_admin_read(pg_temp.a(),'students')$$,'42501',null,'Inactive membership loses reads');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002001',true);
set local role authenticated;
select is(jsonb_array_length(public.get_school_admin_context()->'schools'),2,'Account admin sees descendant schools only');
select lives_ok($$select public.school_admin_read('00000000-0000-0000-0000-000000000012','students')$$,'Account admin can read sibling descendant');
select throws_ok($$select public.school_admin_read('00000000-0000-0000-0000-000000000021','summary')$$,'42501',null,'Account admin cannot read another account');
select lives_ok($$select pg_temp.command(150,'student_update',jsonb_build_object('student_id',pg_temp.student_id(),'first_name','Account','last_name','Updated','student_code','4D2-001'))$$,'Account admin can manage descendants');
reset role;
select is((select actor_scope_kind from public.audit_events where request_id=pg_temp.id(150)),'account','Account-admin audit preserves the real authority scope');
set local role authenticated;
select throws_ok($$select public.platform_list_customers()$$,'42501',null,'Tenant admin cannot provision/read platform');
reset role;
update auth.users set confirmed_at=now() where id='00000000-0000-0000-0000-000000002006';
insert into public.invitations(id,account_id,school_id,scope_kind,role_code,intended_email,token_hash,invited_by,expires_at) values(pg_temp.id(160),'00000000-0000-0000-0000-000000000001',pg_temp.a(),'school','school_admin','foundation-6@example.invalid',repeat('d',64),'00000000-0000-0000-0000-000000001001',now()+interval '7 days');
set local role authenticated;
select throws_ok($$select pg_temp.command(161,'admin_complete',jsonb_build_object('invitation_id',pg_temp.id(160),'display_name','Other customer'))$$,'42501',null,'Identity already linked to another customer cannot be reused');
reset role;
insert into public.school_memberships(account_id,school_id,person_id,role_code) values(pg_temp.id(21),pg_temp.id(22),'00000000-0000-0000-0000-000000001005','school_admin');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002005',true);
set local role authenticated;
select is(public.school_admin_read(pg_temp.id(22),'summary')->'scope'->>'tenant_kind','sandbox','Explicit sandbox tenant membership preserves kind and permits only its scope');
select throws_ok($$select public.school_admin_read('00000000-0000-0000-0000-000000000021','summary')$$,'42501',null,'Explicit sandbox membership does not authorize another customer');
reset role;
select finish();
rollback;
