begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.id(n integer) returns uuid language sql immutable as $$select ('4d300000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.c() returns uuid language sql immutable as $$select '00000000-0000-0000-0000-000000000111'::uuid$$;
create function pg_temp.command(n integer,op text,payload jsonb) returns jsonb language sql as $$select public.cafeteria_admin_command(pg_temp.c(),pg_temp.id(n),op,payload)$$;
create function pg_temp.product_payload(n integer) returns jsonb language sql as $$select jsonb_build_object('id',pg_temp.id(n),'version',null,'name','Synthetic food','description','Test','category','Synthetic lunch','price_minor',19500,'active',true,'available',true,'ingredients',jsonb_build_array('Rice'),'allergens',jsonb_build_array('Milk'))$$;
create function pg_temp.register_payload(n integer) returns jsonb language sql as $$select jsonb_build_object('id',pg_temp.id(n),'version',null,'code','4D3-'||n,'name','Synthetic register','status','active')$$;
create temp table state(k text primary key,v jsonb);
grant all on state to authenticated;
create function pg_temp.invite() returns uuid language sql as $$select (v->>'target_id')::uuid from state where k='invite'$$;
create function pg_temp.member() returns uuid language sql as $$select (v->>'target_id')::uuid from state where k='member'$$;
insert into auth.users(id,aud,role,email,confirmed_at) values(pg_temp.id(1),'authenticated','authenticated','caf-staff@example.invalid',null),(pg_temp.id(2),'authenticated','authenticated','caf-platform@example.invalid',now());
insert into public.persons(id,auth_user_id,display_name) values(pg_temp.id(3),pg_temp.id(2),'Synthetic platform user');
insert into pikas_private.platform_memberships(person_id,role_code) values(pg_temp.id(3),'platform_admin');
select ok(has_function_privilege('authenticated','public.cafeteria_admin_command(uuid,uuid,text,jsonb)','execute') and not has_function_privilege('anon','public.cafeteria_admin_command(uuid,uuid,text,jsonb)','execute'),'Commands authenticated-only');
select ok(not has_function_privilege('service_role','public.cafeteria_admin_command(uuid,uuid,text,jsonb)','execute'),'Service role cannot bypass authority');
select ok(not has_table_privilege('authenticated','pikas_private.cafeteria_admin_requests','select'),'Journal private');
select set_config('request.jwt.claim.sub','',true);set local role authenticated;
select is(public.get_cafeteria_admin_context(),null::jsonb,'No unauthenticated workspace');
select throws_ok($$select public.cafeteria_admin_read(pg_temp.c())$$,'42501',null,'Unauthenticated read denied');
reset role;select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);set local role authenticated;
select is(jsonb_array_length(public.get_cafeteria_admin_context()->'cafeterias'),0,'Platform-only has no cafeteria authority');
select throws_ok($$select pg_temp.command(100,'register_save',pg_temp.register_payload(10))$$,'42501',null,'Platform-only command denied');
reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002002',true);set local role authenticated;
select is(jsonb_array_length(public.get_cafeteria_admin_context()->'cafeterias'),0,'School authority does not imply cafeteria administration');
select throws_ok($$select public.cafeteria_admin_read(pg_temp.c())$$,'42501',null,'School-only read denied');
reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002003',true);set local role authenticated;
select is(jsonb_array_length(public.get_cafeteria_admin_context()->'cafeterias'),1,'Explicit cafeteria membership resolves intended workspace');
select is(public.cafeteria_admin_read(pg_temp.c())->'scope'->>'cafeteria_id',pg_temp.c()::text,'Read scoped cafeteria');
select is(public.cafeteria_admin_read(pg_temp.c())->'scope'->>'tenant_kind','customer','Customer boundary explicit');
select throws_ok($$select public.cafeteria_admin_read('00000000-0000-0000-0000-000000000112')$$,'42501',null,'Sibling cafeteria denied');
select throws_ok($$select public.cafeteria_admin_read('00000000-0000-0000-0000-000000000211')$$,'42501',null,'Other account denied');
select throws_ok($$select pg_temp.command(101,'staff_prepare','{"email":"x@example.invalid","role":"school_admin"}')$$,'22023',null,'Staff cannot grant school authority');
select throws_ok($$select pg_temp.command(102,'staff_complete','{"invitation_id":"4d300000-0000-4000-8000-000000000001","display_name":"X","auth_id":"4d300000-0000-4000-8000-000000000002"}')$$,'22023',null,'Browser Auth UUID rejected');
select throws_ok($$select pg_temp.command(103,'product_save',pg_temp.product_payload(20)||'{"actor_id":"4d300000-0000-4000-8000-000000000001"}')$$,'22023',null,'Browser actor rejected');
select throws_ok($$select pg_temp.command(104,'product_save',pg_temp.product_payload(20)||'{"price_minor":-1}')$$,'22023',null,'Negative price rejected');
select throws_ok($$select pg_temp.command(105,'product_save',pg_temp.product_payload(20)||'{"price_minor":19.5}')$$,'22023',null,'Fractional minor units rejected');
select lives_ok($$select pg_temp.command(106,'product_save',pg_temp.product_payload(20))$$,'Product and category create via existing contracts');
select lives_ok($$select pg_temp.command(106,'product_save',pg_temp.product_payload(20))$$,'Product replay resolves original result');
select throws_ok($$select pg_temp.command(106,'product_save',pg_temp.product_payload(20)||'{"price_minor":20000}')$$,'23505',null,'Changed retry payload denied');
select is(jsonb_array_length(public.cafeteria_admin_read(pg_temp.c())->'products'),5,'Scoped catalog includes synthetic product and four existing products');
select lives_ok($$select pg_temp.command(107,'product_save',pg_temp.product_payload(20)||'{"version":1,"price_minor":20000,"available":false}')$$,'Product edit authoritatively changes minor-unit price and availability');
select throws_ok($$select pg_temp.command(108,'product_save',pg_temp.product_payload(20)||'{"version":1}')$$,'40001',null,'Stale product edit rejected');
select lives_ok($$select pg_temp.command(109,'category_save',jsonb_build_object('id',pg_temp.id(21),'version',null,'name','Synthetic other','display_order',1,'status','active'))$$,'Category create');
select lives_ok($$select pg_temp.command(110,'category_save',jsonb_build_object('id',pg_temp.id(21),'version',1,'name','Synthetic renamed','display_order',2,'status','archived'))$$,'Category edit/archive');
select lives_ok($$select pg_temp.command(111,'menu_save',jsonb_build_object('id',pg_temp.id(30),'version',null,'name','Synthetic menu','description','','active',true,'product_ids',jsonb_build_array(pg_temp.id(20))))$$,'Menu and product membership atomic');
select lives_ok($$select pg_temp.command(112,'menu_save',jsonb_build_object('id',pg_temp.id(30),'version',2,'name','Synthetic menu','description','','active',true,'product_ids','[]'::jsonb))$$,'Menu product removal');
select lives_ok($$select pg_temp.command(113,'shift_save',jsonb_build_object('id',pg_temp.id(31),'version',null,'menu_id',pg_temp.id(30),'name','Synthetic shift','start_time','23:00','end_time','23:30','enabled',false,'weekdays',jsonb_build_array(1,2)))$$,'Real same-day service shift contract');
select lives_ok($$select pg_temp.command(114,'settings_save','{"version":1,"scheduling_enabled":true}')$$,'Supported settings connected');
select throws_ok($$select pg_temp.command(115,'settings_save','{"version":1,"scheduling_enabled":false}')$$,'40001',null,'Stale settings rejected');
select lives_ok($$select pg_temp.command(116,'register_save',pg_temp.register_payload(40))$$,'Register creation is scoped');
select lives_ok($$select pg_temp.command(116,'register_save',pg_temp.register_payload(40))$$,'Register replay idempotent');
select throws_ok($$select pg_temp.command(117,'register_save',pg_temp.register_payload(41)||jsonb_build_object('code','4D3-40'))$$,'23505',null,'Duplicate register code denied');
select lives_ok($$select pg_temp.command(118,'register_save',pg_temp.register_payload(40)||'{"version":1,"name":"Synthetic edited"}')$$,'Register configuration reused');
insert into state values('invite',pg_temp.command(119,'staff_prepare','{"email":"caf-staff@example.invalid","role":"pos_cashier"}'));
select throws_ok($$select pg_temp.command(120,'staff_complete',jsonb_build_object('invitation_id',pg_temp.invite(),'display_name','Synthetic staff'))$$,'23514','confirmed_identity_pending','Unconfirmed identity stays pending without authority');
reset role;update auth.users set confirmed_at=now() where id=pg_temp.id(1);set local role authenticated;
insert into state values('member',pg_temp.command(120,'staff_complete',jsonb_build_object('invitation_id',pg_temp.invite(),'display_name','Synthetic staff')));
select lives_ok($$select pg_temp.command(120,'staff_complete',jsonb_build_object('invitation_id',pg_temp.invite(),'display_name','Synthetic staff'))$$,'Staff replay returns original grant');
select lives_ok($$select pg_temp.command(121,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id',pg_temp.id(40),'status','active','version',null))$$,'Eligible cafeteria cashier assigned');
select lives_ok($$select pg_temp.command(121,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id',pg_temp.id(40),'status','active','version',null))$$,'Assignment replay idempotent');
select throws_ok($$select pg_temp.command(122,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id','00000000-0000-0000-0000-000000004702','status','active','version',null))$$,'42501',null,'Foreign register assignment denied');
select throws_ok($$select pg_temp.command(123,'staff_status',jsonb_build_object('membership_id','00000000-0000-0000-0000-000000003202','status','active'))$$,'42501',null,'Cafeteria-admin membership cannot become POS staff');
insert into state values('assignment',pg_temp.command(121,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id',pg_temp.id(40),'status','active','version',null)));
select ok(public.cafeteria_admin_read(pg_temp.c())::text !~ 'auth_user_id|token_hash|banned_until|authenticated_user_id','Customer-facing projection contains no Auth/security metadata');
reset role;
select is((select count(*) from public.persons where auth_user_id=pg_temp.id(1)),1::bigint,'One linked Person');
select is((select count(*) from public.cafeteria_memberships m join public.persons p on p.id=m.person_id where p.auth_user_id=pg_temp.id(1)),1::bigint,'One cafeteria membership');
select is((select count(*) from public.audit_events where request_id=pg_temp.id(120)),1::bigint,'One real-actor command audit on replay');
select is((select actor_person_id from public.audit_events where request_id=pg_temp.id(120)),'00000000-0000-0000-0000-000000001003'::uuid,'Audit attributes actual admin');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);set local role authenticated;
select is(jsonb_array_length(public.get_cafeteria_admin_context()->'cafeterias'),0,'POS staff does not acquire administration');
select lives_ok($$select public.open_register_session(pg_temp.id(40),(select (v->>'target_id')::uuid from state where k='assignment'),0,'4d3-open-register-session')$$,'Newly configured register supports existing POS session');
reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002003',true);set local role authenticated;
select throws_ok($$select pg_temp.command(124,'register_save',pg_temp.register_payload(40)||'{"version":2,"name":"Unsafe open edit"}')$$,'23514','open_register_configuration_locked','Open session blocks unsafe register edit');
select lives_ok($$select pg_temp.command(125,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id',pg_temp.id(40),'status','inactive','version',1))$$,'Assignment removal preserves session history');
select lives_ok($$select pg_temp.command(126,'staff_status',jsonb_build_object('membership_id',pg_temp.member(),'status','suspended'))$$,'Staff suspended within cafeteria');
select throws_ok($$select pg_temp.command(127,'assignment_save',jsonb_build_object('membership_id',pg_temp.member(),'register_id',pg_temp.id(40),'status','active','version',2))$$,'23514',null,'Suspended staff cannot be assigned');
reset role;update public.cafeteria_memberships set status='suspended' where id='00000000-0000-0000-0000-000000003201';set local role authenticated;
select is(jsonb_array_length(public.get_cafeteria_admin_context()->'cafeterias'),0,'Suspended admin scope absent');
select throws_ok($$select pg_temp.command(116,'register_save',pg_temp.register_payload(40))$$,'42501',null,'Revoked authority cannot recover past successful write');
reset role;update public.cafeteria_memberships set status='inactive' where id='00000000-0000-0000-0000-000000003201';set local role authenticated;
select throws_ok($$select public.cafeteria_admin_read(pg_temp.c())$$,'42501',null,'Inactive admin denied');
reset role;
-- Cross-scope writes fail even when a supplied object ID is well formed.
update public.cafeteria_memberships set status='active' where id='00000000-0000-0000-0000-000000003201';
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002004',true);set local role authenticated;
select public.cafeteria_admin_command('00000000-0000-0000-0000-000000000112',pg_temp.id(130),'product_save',pg_temp.product_payload(25));
reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000002003',true);set local role authenticated;
select throws_ok($$select pg_temp.command(131,'product_save',pg_temp.product_payload(25)||'{"version":1}')$$,'23503',null,'Foreign cafeteria product cannot be edited');
select throws_ok($$select pg_temp.command(132,'menu_save',jsonb_build_object('id',pg_temp.id(32),'version',null,'name','Foreign product menu','description','','active',true,'product_ids',jsonb_build_array(pg_temp.id(25))))$$,'23503',null,'Foreign product cannot enter a scoped menu');
select throws_ok($$select pg_temp.command(133,'shift_save',jsonb_build_object('id',pg_temp.id(33),'version',null,'menu_id','00000000-0000-0000-0000-000000009003','name','Foreign menu shift','start_time','20:00','end_time','21:00','enabled',true,'weekdays',jsonb_build_array(1)))$$,'23503',null,'Foreign menu cannot supply service shift');
select throws_ok($$select pg_temp.command(134,'register_save',pg_temp.register_payload(40)||'{"id":"00000000-0000-0000-0000-000000009403","version":1}')$$,'42501',null,'Foreign register cannot be modified');
select throws_ok($$select pg_temp.command(135,'assignment_save',jsonb_build_object('membership_id','00000000-0000-0000-0000-000000004602','register_id',pg_temp.id(40),'status','active','version',null))$$,'42501',null,'Foreign cafeteria membership cannot be assigned');
select throws_ok($$select pg_temp.command(136,'staff_status','{"membership_id":"00000000-0000-0000-0000-000000004602","status":"active"}')$$,'42501',null,'Foreign cafeteria staff cannot be reactivated');
select throws_ok($$select pg_temp.command(137,'settings_save','{"version":2,"scheduling_enabled":false,"allowCashierRefunds":true}')$$,'22023',null,'Unsupported financial policy not accepted');
reset role;
select is((select count(*) from public.cafeteria_menus where id=pg_temp.id(32)),0::bigint,'Failed menu transaction leaves no partial menu');
select is((select count(*) from pikas_private.cafeteria_admin_requests where request_id=pg_temp.id(132)),0::bigint,'Failed command leaves no success journal');
-- A sandbox requires its own explicit membership; its IDs cannot be used against customer scope.
insert into public.accounts(id,code,name,tenant_kind) values(pg_temp.id(50),'4D3-SANDBOX','Synthetic sandbox','sandbox');
insert into public.schools(id,account_id,code,name) values(pg_temp.id(51),pg_temp.id(50),'S','Synthetic sandbox school');
insert into public.school_locations(id,account_id,school_id,code,name) values(pg_temp.id(52),pg_temp.id(50),pg_temp.id(51),'L','Synthetic sandbox campus');
insert into public.cafeterias(id,account_id,school_id,school_location_id,code,name) values(pg_temp.id(53),pg_temp.id(50),pg_temp.id(51),pg_temp.id(52),'C','Synthetic sandbox cafeteria');
set local role authenticated;
select throws_ok($$select public.cafeteria_admin_read(pg_temp.id(53))$$,'42501',null,'Customer authority alone cannot enter sandbox');
reset role;
insert into public.cafeteria_memberships(account_id,school_id,cafeteria_id,person_id,role_code) values(pg_temp.id(50),pg_temp.id(51),pg_temp.id(53),'00000000-0000-0000-0000-000000001003','cafeteria_admin');
set local role authenticated;
select is(public.cafeteria_admin_read(pg_temp.id(53))->'scope'->>'tenant_kind','sandbox','Explicit sandbox membership preserves tenant label');
select throws_ok($$select public.cafeteria_admin_command(pg_temp.id(53),pg_temp.id(138),'product_save',pg_temp.product_payload(20)||'{"version":2}')$$,'23503',null,'Sandbox command cannot modify customer product');
select throws_ok($$select public.cafeteria_admin_command(pg_temp.id(53),pg_temp.id(139),'register_save',pg_temp.register_payload(40)||'{"version":2}')$$,'42501',null,'Sandbox command cannot modify customer register');
reset role;
-- Confirmed identity does not grant authority by email and platform identities cannot be onboarded.
set local role authenticated;
insert into state values('platform-invite',pg_temp.command(140,'staff_prepare','{"email":"caf-platform@example.invalid","role":"pos_supervisor"}'));
select throws_ok($$select pg_temp.command(141,'staff_complete',jsonb_build_object('invitation_id',(select v->>'target_id' from state where k='platform-invite'),'display_name','Synthetic platform staff'))$$,'42501',null,'Platform identity cannot be linked as customer staff');
reset role;
update auth.users set confirmed_at=null where id=pg_temp.id(1);
set local role authenticated;
select throws_ok($$select pg_temp.command(142,'staff_status',jsonb_build_object('membership_id',pg_temp.member(),'status','active'))$$,'23514','active_confirmed_pos_identity_required','Unconfirmed staff cannot be reactivated');
reset role;
select * from finish();
rollback;
