import { openDemoRegister } from './helpers';
import { test, expect, type Page } from '@playwright/test';
import { invoke, snapshot } from './helpers';
async function admin(page: Page, path = '/admin/cafeteria/menus') {
  await page.goto('/admin/login');
  await page.getByLabel('Correo demo').filter({ visible: true }).fill('admin.cafeteria@demo.pikas.do');
  await page.getByRole('button', { name: 'Entrar a administración' }).click();
  await page.goto(path);
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
}
async function saveMenu(page: Page, name: string) {
  await page.getByRole('button', { name: 'Crear menú', exact: true }).click();
  await page.getByLabel('Nombre del menú', { exact: true }).fill(name);
  await page.getByLabel('Buscar productos para el menú').fill('Pasta');
  await page.getByRole('button', { name: 'Añadir Pasta con pollo' }).click();
  await page.getByRole('button', { name: 'Guardar menú' }).click();
  await expect(page.getByRole('status')).toContainText('Menú guardado');
}
async function fillShift(page: Page, name: string, start: string, end: string) {
  await page.getByRole('button', { name: 'Crear turno de servicio', exact: true }).click();
  await page.getByLabel('Nombre del turno').fill(name);
  await page.getByRole('checkbox', { name: 'Lunes', exact: true }).check();
  await page.getByLabel('Hora de inicio').fill(start);
  await page.getByLabel('Hora de fin').fill(end);
}
test('menus reference shared products, preserve metadata and remove membership only', async ({ page }) => {
  test.setTimeout(60000);
  await admin(page); await saveMenu(page, 'Desayuno'); await saveMenu(page, 'Almuerzo');
  let state = await snapshot(page);
  expect(state.menuItems).toHaveLength(5); expect(state.cafeteriaOperations.menuProducts).toHaveLength(2);
  const pasta = state.menuItems.find((item: { id: string }) => item.id === 'menu-pasta');
  expect((await invoke(page, 'adminUpdateMenu', [{ ...pasta, priceMinor: 19500 }])).ok).toBe(true);
  await page.getByRole('button', { name: 'Editar menú Desayuno' }).click();
  await page.getByRole('button', { name: 'Ver seleccionados' }).click();
  await expect(page.getByRole('button', { name: 'Quitar Pasta con pollo' }).locator('..')).toContainText('195.00');
  await page.getByLabel('Descripción del menú').fill('Mañana escolar');
  await page.getByRole('button', { name: 'Quitar Pasta con pollo' }).click();
  await page.getByRole('checkbox', { name: 'Menú activo' }).uncheck();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Guardar menú' }).click();
  await expect(page.getByRole('status')).toContainText('Menú guardado');
  state = await snapshot(page);
  expect(state.menuItems).toHaveLength(5); expect(state.cafeteriaOperations.menuProducts).toHaveLength(1);
  expect(state.cafeteriaOperations.menus.find((menu: { name: string }) => menu.name === 'Desayuno')).toMatchObject({ active: false, description: 'Mañana escolar' });
  await page.reload();
  await expect(page.getByRole('article').filter({ hasText: 'Desayuno' })).toContainText('Inactivo');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('service shift creation, conflicts, disabled state, global suspension and inactive menus', async ({ page }) => {
  test.setTimeout(90000);
  await admin(page); await saveMenu(page, 'Desayuno');
  await page.getByRole('link', { name: 'Turnos de servicio', exact: true }).click();
  await fillShift(page, 'Mañana', '07:00', '10:00');
  await page.getByRole('button', { name: 'Guardar turno' }).click();
  await expect(page.getByRole('status')).toContainText('guardado');
  await fillShift(page, 'Mediodía', '09:00', '12:00');
  await page.getByRole('button', { name: 'Guardar turno' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'superponerse' })).toBeVisible();
  await page.getByLabel('Hora de inicio').fill('22:00'); await page.getByLabel('Hora de fin').fill('06:00');
  await page.getByRole('button', { name: 'Guardar turno' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'mismo día' })).toBeVisible();
  await page.getByLabel('Hora de inicio').fill('10:00'); await page.getByLabel('Hora de fin').fill('12:00');
  await page.getByRole('button', { name: 'Guardar turno' }).click();
  await expect(page.getByRole('status')).toContainText('guardado');
  await page.getByRole('button', { name: 'Editar turno Mediodía' }).click();
  await page.getByRole('checkbox', { name: 'Martes', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Turno habilitado' }).uncheck();
  await page.getByRole('button', { name: 'Guardar turno' }).click();
  await expect(page.getByRole('status')).toContainText('guardado');
  const shifts = (await snapshot(page)).cafeteriaOperations.serviceShifts;
  expect(shifts[1]).toMatchObject({ enabled: false, weekdays: [1, 2] });
  const toggle = page.getByRole('switch', { name: 'Activar turnos de servicio' });
  await toggle.click(); await expect(toggle).toHaveAttribute('aria-checked', 'true');
  page.once('dialog', dialog => dialog.accept()); await toggle.click(); await expect(toggle).toHaveAttribute('aria-checked', 'false');
  await toggle.click(); await expect(toggle).toHaveAttribute('aria-checked', 'true');
  expect((await snapshot(page)).cafeteriaOperations.serviceShifts).toEqual(shifts);
  await page.goto('/admin/cafeteria/menus'); await page.getByRole('button', { name: 'Editar menú Desayuno' }).click();
  await page.getByRole('checkbox', { name: 'Menú activo' }).uncheck(); page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Guardar menú' }).click(); await expect(page.getByRole('status')).toContainText('guardado');
  await page.goto('/admin/cafeteria/menus/turnos');
  await page.getByRole('button', { name: 'Editar turno Mañana' }).click();
  await expect(page.getByRole('status')).toContainText('menú está inactivo');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `/tmp/pikas-service-${test.info().project.name}.png`, fullPage: true });
  await page.goto('/login'); await page.getByRole('tab', { name: 'Cafetería' }).click(); await page.getByRole('button', { name: /Entrar como cafetería/ }).click(); await openDemoRegister(page);
  await page.getByRole('button', { name: 'No usuario', exact: true }).click();
  await expect(page.getByRole('article').filter({ hasText: 'Pasta con pollo' })).toHaveCount(0);
});
test('uploaded and gallery images persist, replace and remove without altering historical purchases', async ({ page }) => {
  test.setTimeout(90000);
  await page.goto('/login'); await page.getByRole('tab', { name: 'Cafetería' }).click(); await page.getByRole('button', { name: /Entrar como cafetería/ }).click(); await openDemoRegister(page);
  expect((await invoke(page, 'checkoutPos', [null, [{ itemId: 'menu-pasta', quantity: 1 }], 'image-history', 'cash', 18000, true])).ok).toBe(true);
  const purchases = (await snapshot(page)).purchases;
  await admin(page, '/admin/cafeteria/productos');
  await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click();
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 40; canvas.height = 40; const context = canvas.getContext('2d')!; context.fillStyle = '#fbbf24'; context.fillRect(0, 0, 40, 40); return canvas.toDataURL('image/png').split(',')[1]!; });
  const file = page.getByLabel('Subir imagen del producto');
  await file.setInputFiles({ name: 'bad.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') });
  await expect(page.getByRole('alert').filter({ hasText: 'JPG' })).toBeVisible();
  await file.setInputFiles({ name: 'big.png', mimeType: 'image/png', buffer: Buffer.alloc(5 * 1024 * 1024 + 1) });
  await expect(page.getByRole('alert').filter({ hasText: '5 MB' })).toBeVisible();
  await file.setInputFiles({ name: 'food.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await expect(page.getByRole('button', { name: 'Subir imagen', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Guardar cambios' }).click(); await expect(page.getByRole('status')).toContainText('actualizado');
  const upload = (await snapshot(page)).menuItems.find((item: { id: string }) => item.id === 'menu-pasta').imageUrl;
  expect(upload).toMatch(/^data:image\/(webp|png);base64,/); expect(upload.length).toBeLessThanOrEqual(65536);
  await page.reload(); await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click();
  await page.getByLabel('Descripción', { exact: true }).fill('Descripción nueva');
  await page.getByRole('button', { name: 'Guardar cambios' }).click(); await expect(page.getByRole('status')).toContainText('actualizado');
  expect((await snapshot(page)).menuItems.find((item: { id: string }) => item.id === 'menu-pasta').imageUrl).toBe(upload);
  await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click();
  await page.getByRole('button', { name: 'Galería PIKAS', exact: true }).click();
  await page.getByRole('button', { name: 'Seleccionar Pizza' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `/tmp/pikas-image-editor-${test.info().project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Guardar cambios' }).click(); await expect(page.getByRole('status')).toContainText('actualizado');
  expect((await snapshot(page)).menuItems.find((item: { id: string }) => item.id === 'menu-pasta')).toMatchObject({ imageAssetId: 'pikas-food-003', imageUrl: '/menu/pizza.svg' });
  await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click(); await page.getByRole('button', { name: 'Quitar imagen' }).click();
  await page.getByRole('button', { name: 'Guardar cambios' }).click(); await expect(page.getByRole('status')).toContainText('actualizado');
  expect((await snapshot(page)).menuItems.find((item: { id: string }) => item.id === 'menu-pasta').imageUrl).toBeNull();
  expect((await snapshot(page)).purchases).toEqual(purchases);
});
