import {confirmSale} from './helpers';
import {test,expect,type Page} from '@playwright/test';
const key='pikas:unified-demo:v2';
async function pos(page:Page){await page.goto('/login');await page.getByRole('tab',{name:'Cafetería'}).click();await page.getByRole('button',{name:'Entrar como cafetería'}).click();await expect(page.getByRole('button',{name:'Usuario PIKAS',exact:true})).toBeVisible()}
async function identify(page:Page,code='PK-10982'){await page.getByRole('button',{name:'Usuario PIKAS',exact:true}).click();await page.getByLabel('Código estudiantil / NFC').filter({visible:true}).fill(code);await page.getByRole('button',{name:'Comprobar estudiante'}).click();await expect(page.getByRole('heading',{name:code==='PK-10982'?'Sofi':'Mateo',exact:true})).toBeVisible()}
async function add(page:Page,name='Pasta con pollo'){await page.getByRole('article').filter({hasText:name}).getByRole('button',{name:'Añadir al carrito'}).click()}
async function pay(page:Page){await page.getByRole('button',{name:'Continuar al pago'}).click();await confirmSale(page);await expect(page.getByRole('heading',{name:'Compra completada'})).toBeVisible()}
async function admin(page:Page){await page.context().clearCookies();await page.goto('/admin/login');await page.getByRole('textbox',{name:'Correo demo'}).fill('admin.cafeteria@demo.pikas.do');await page.getByRole('button',{name:'Entrar a administración'}).click();await expect(page).toHaveURL(/\/admin\/cafeteria$/)}
async function data(page:Page){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)??'{}'),key)}
async function mutate(page:Page,change:string){await page.evaluate(({key,change})=>{const state=JSON.parse(localStorage.getItem(key)??'{}');new Function('state',change)(state);localStorage.setItem(key,JSON.stringify(state))},{key,change});await page.reload()}
async function persist(page:Page){await page.evaluate(k=>{if(!localStorage.getItem(k))throw new Error('State should have been persisted')},key)}

test('guided entry, scoped name search and customer changes preserve conflicting cart',async({page})=>{
  await pos(page);await expect(page.getByRole('heading',{name:'Productos',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'No usuario',exact:true}).click();await expect(page.getByRole('heading',{name:'Top 5 cliente'})).toHaveCount(0);await add(page,'Pizza escolar');
  await page.getByRole('button',{name:'Buscar usuario PIKAS'}).click();await page.getByLabel('Código estudiantil / NFC').filter({visible:true}).fill('Sof');await page.getByRole('button',{name:/Sofi Rosa/}).click();
  await expect(page.getByRole('heading',{name:'Carrito persistente'}).locator('..')).toContainText('Pizza escolar');await page.getByRole('button',{name:'Continuar al pago'}).click();await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeDisabled();await expect(page.getByRole('alert').filter({hasText:'Lactosa'})).toBeVisible();
  await page.getByRole('button',{name:'Cambiar cliente'}).click();await identify(page,'PK-11804');await expect(page.getByRole('heading',{name:'Carrito persistente'}).locator('..')).toContainText('Pizza escolar');await pay(page);
  await persist(page);await mutate(page,"state.students.push({...state.students[0],id:'outside',preferredName:'Hidden',firstName:'Hidden',code:'PK-99999',schoolName:'Unauthorized school'})");await page.getByRole('button',{name:'Usuario PIKAS',exact:true}).click();await page.getByLabel('Código estudiantil / NFC').filter({visible:true}).fill('Hidden');await expect(page.getByRole('button',{name:/Hidden/})).toHaveCount(0);
});

test('cash amount, change, completion and new transaction; calculator does not change cart',async({page})=>{
  await pos(page);await page.getByRole('button',{name:'No usuario',exact:true}).click();await add(page);await page.getByRole('button',{name:'Calculadora',exact:true}).click();await page.keyboard.type('25+50');await page.keyboard.press('Enter');await expect(page.getByLabel('Resultado de calculadora')).toHaveText('75');await page.getByRole('button',{name:'Cerrar calculadora'}).click();await page.getByRole('button',{name:'Continuar al pago'}).click();await page.getByLabel('Efectivo recibido (RD$)').filter({visible:true}).fill('100');await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeDisabled();await page.getByLabel('Efectivo recibido (RD$)').filter({visible:true}).fill('1000');await expect(page.getByText(/Cambio: RD\$820/).filter({visible:true})).toBeVisible();await confirmSale(page);await expect(page.getByRole('heading',{name:'Compra completada'})).toBeVisible();await page.getByRole('button',{name:'Ver recibo'}).click();await expect(page.getByLabel('Detalle de transacción').filter({visible:true})).toContainText('Caja Demo');await expect(page.getByRole('button',{name:'Confirmar reembolso'})).toHaveCount(0);const saved=await data(page);expect(saved.purchases).toHaveLength(1);expect(saved.purchases[0]).toMatchObject({studentId:null,cashReceivedMinor:100000,changeProvidedMinor:82000});await page.getByRole('button',{name:'Nueva transacción'}).click();await expect(page.getByRole('button',{name:'Usuario PIKAS',exact:true})).toBeVisible();
});

test('daily limit, replenishment, independent students and offline rejection',async({page,context})=>{
  await pos(page);await identify(page);await add(page);await pay(page);await mutate(page,"state.students[0].balance=1; state.students[0].dailyLimit=350");await identify(page);await add(page);await page.getByRole('button',{name:'Continuar al pago'}).click();await page.getByRole('button',{name:'Recargar saldo',exact:true}).click();await page.getByRole('button',{name:'Confirmar recarga'}).click();await expect(page.getByRole('alert').filter({hasText:'Recarga completada'})).toBeVisible();let saved=await data(page);expect(saved.events.filter((e:{type:string})=>e.type==='replenishment')).toHaveLength(1);expect(saved.students[0]).toMatchObject({balance:501,spentToday:340});await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeDisabled();await expect(page.getByText('El total supera lo que queda del límite diario.').filter({visible:true})).toBeVisible();await page.getByRole('button',{name:'Cambiar cliente'}).click();await identify(page,'PK-11804');await page.getByRole('button',{name:'Continuar al pago'}).click();await context.setOffline(true);await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeDisabled();await expect(page.getByLabel('Estado de caja').filter({visible:true})).toContainText('Offline');await context.setOffline(false);await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeEnabled();saved=await data(page);expect(saved.students[1].spentToday).toBe(105);
});

test('admin policy controls cashier visibility; refund is linked and visible to parent',async({page})=>{
  await pos(page);await identify(page);await add(page);await pay(page);const before=await data(page),purchase=before.purchases[0];
  await admin(page);await page.goto('/admin/cafeteria/configuracion');await expect(page.getByLabel('Permitir reembolsos de caja').filter({visible:true})).not.toBeChecked();await page.getByLabel('Mostrar ventas del turno').filter({visible:true}).uncheck();await expect(page.getByRole('status')).toHaveText('Configuración guardada.');await page.getByLabel('Permitir reembolsos de caja').filter({visible:true}).check();await expect(page.getByLabel('Requerir aprobación administrativa').filter({visible:true})).toBeEnabled();await page.getByLabel('Requerir aprobación administrativa').filter({visible:true}).uncheck();await expect(page.getByLabel('Permitir reembolsos parciales').filter({visible:true})).toBeEnabled();await page.getByLabel('Permitir reembolsos parciales').filter({visible:true}).check();await expect(page.getByLabel('Permitir reembolsos parciales').filter({visible:true})).toBeEnabled();
  await page.context().clearCookies();await pos(page);await expect(page.getByTestId('shift-sales')).toHaveCount(0);await page.getByRole('button',{name:'Transacciones',exact:true}).click();await page.getByRole('button',{name:/Sofi.*Pasta/}).click();await page.getByLabel('Monto del reembolso (RD$)').filter({visible:true}).fill('100');await page.getByLabel('Motivo',{exact:true}).filter({visible:true}).fill('Artículo no entregado');await page.getByRole('button',{name:'Revisar reembolso'}).click();await page.getByRole('button',{name:'Confirmar reembolso'}).click();await expect(page.getByRole('status')).toHaveText('Reembolso completado.');await expect(page.getByLabel('Recibo de reembolso')).toBeVisible();await expect(page.getByText('Recibo de reembolso',{exact:true})).toBeVisible();const after=await data(page);expect(after.purchases[0]).toEqual(purchase);expect(after.students[0]).toMatchObject({spentToday:240,balance:2370});expect(after.events[0]).toMatchObject({type:'refund',originalPurchaseId:purchase.id,amountMinor:10000,actorId:'pos-1'});
  await page.context().clearCookies();await page.goto('/login');await page.getByRole('button',{name:'Entrar como familia'}).click();await page.goto('/familias/transacciones');await page.getByText(/Reembolso \+RD\$100/).filter({visible:true}).click();await expect(page.getByText('Procesado por: Caja Demo').filter({visible:true})).toBeVisible();await expect(page.getByText(`Compra original: ${purchase.id}`).filter({visible:true})).toBeVisible();
});

test('parent daily-limit switch persists independently per student',async({page})=>{
  await page.goto('/login');await page.getByRole('button',{name:'Entrar como familia'}).click();await page.goto('/familias/estudiantes/sofia');await page.getByRole('checkbox',{name:'Límite diario activado'}).uncheck();await page.getByLabel('Límite diario',{exact:true}).filter({visible:true}).fill('500');await page.getByRole('button',{name:'Guardar cambios'}).click();await expect(page.getByRole('status')).toHaveText('Cambios guardados.');await page.reload();await expect(page.getByRole('checkbox',{name:'Límite diario activado'})).not.toBeChecked();const saved=await data(page);expect(saved.students[0]).toMatchObject({dailyLimit:500,dailyLimitEnabled:false});expect(saved.students[1].dailyLimit).toBe(300);
});

test('recommendation scenario fills ten distinct products and retains restrictions',async({page})=>{
  await admin(page);await page.goto('/admin/cafeteria/configuracion');await page.getByRole('button',{name:'Cargar historial de recomendaciones'}).click();await expect(page.getByRole('status')).toHaveText('Historial ficticio cargado.');await page.context().clearCookies();await pos(page);await identify(page);
  const cafeteria=page.getByRole('heading',{name:'Top 5 cafetería'}).locator('..');await expect(cafeteria.getByRole('button')).toHaveCount(5);await page.getByRole('button',{name:'Frecuentes',exact:true}).click();const customer=page.locator('.pos-product-tile');await expect(customer).toHaveCount(5);const names=[...await cafeteria.getByRole('button').allTextContents(),...await customer.allTextContents()];expect(new Set(names).size).toBe(10);
});

test('two tabs cannot overspend the same daily allowance',async({page,context})=>{
  await pos(page);await identify(page);await add(page);await page.getByRole('button',{name:'Continuar al pago'}).click();const firstKey=await page.evaluate(()=>JSON.parse(localStorage.getItem('pikas:pos-cart:v1')!).key);await page.evaluate(()=>localStorage.removeItem('pikas:pos-cart:v1'));const other=await context.newPage();await other.goto('/pos');await identify(other);await add(other);await other.getByRole('button',{name:'Continuar al pago'}).click();
  const secondKey=await other.evaluate(()=>JSON.parse(localStorage.getItem('pikas:pos-cart:v1')!).key);expect(secondKey).not.toBe(firstKey);await expect(page.getByRole('button',{name:'Confirmar venta'})).toBeEnabled();await expect(other.getByRole('button',{name:'Confirmar venta'})).toBeEnabled();
  // Fire both handlers before storage notifications can disable the second button.
  const confirmations=[page.waitForResponse(r=>r.url().endsWith('/api/demo/session')),other.waitForResponse(r=>r.url().endsWith('/api/demo/session'))];
  await Promise.all([page.getByRole('button',{name:'Confirmar venta'}).evaluate((el:HTMLButtonElement)=>el.click()),other.getByRole('button',{name:'Confirmar venta'}).evaluate((el:HTMLButtonElement)=>el.click())]);
  await Promise.all(confirmations);
  for(const tab of [page,other])await expect(tab.getByRole('button',{name:'Procesando…',exact:true})).toHaveCount(0);
  expect(await page.getByRole('heading',{name:'Compra completada'}).count()+await other.getByRole('heading',{name:'Compra completada'}).count()).toBe(1);
  await expect.poll(async()=>{const snapshot=await data(page);return snapshot.purchases?.length??0}).toBe(1);const saved=await data(page);expect(saved.students[0]).toMatchObject({spentToday:340,balance:2270});await other.close();
});

test('POS mobile and desktop screens have no overflow or runtime errors',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await pos(page);await page.screenshot({path:testInfo.outputPath('pos-entry.png')});await identify(page);await add(page);await page.getByRole('button',{name:'Continuar al pago'}).click();await page.getByRole('button',{name:'Elegir efectivo'}).click();await page.getByRole('button',{name:'Monto exacto'}).click();await page.getByRole('button',{name:'Confirmar venta'}).scrollIntoViewIfNeeded();const statusBox=await page.locator('footer[aria-label="Estado de caja"]:visible').boundingBox();expect(statusBox?.y).toBeGreaterThanOrEqual(0);expect(statusBox!.y+statusBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);await page.screenshot({path:testInfo.outputPath('pos-payment.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await confirmSale(page);await expect(page.getByRole('heading',{name:'Compra completada'})).toBeVisible();expect(errors).toEqual([]);
});

test('administrator full refund preserves historical spending allowance and attribution',async({page})=>{
  await pos(page);await identify(page);await add(page);await pay(page);await mutate(page,"state.purchases[0].createdAt=new Date(Date.now()-86400000).toISOString();state.students[0].spentToday=80");await admin(page);await page.goto('/admin/cafeteria/transacciones');await page.getByRole('button',{name:/Sofi.*Pasta/}).click();await page.getByRole('textbox',{name:'Motivo',exact:true}).fill('Devolución de compra anterior');await page.getByRole('button',{name:'Revisar reembolso'}).click();await page.getByRole('button',{name:'Confirmar reembolso'}).click();await expect(page.getByRole('status').filter({hasText:'Reembolso completado.'})).toBeVisible();const saved=await data(page);expect(saved.students[0]).toMatchObject({balance:2450,spentToday:80});expect(saved.events[0]).toMatchObject({approvedBy:'ca-1',actorId:'ca-1',amountMinor:18000});await expect(page.getByRole('button',{name:'Revisar reembolso'})).toHaveCount(0);
});


test('checkout retry key survives refresh and prevents a second charge',async({page})=>{
  await pos(page);await identify(page);await add(page);const pending=await page.evaluate(()=>localStorage.getItem('pikas:pos-cart:v1'));expect(JSON.parse(pending!).key).toBeTruthy();await pay(page);const before=await data(page);
  // Simulate a crash after saving the purchase but before clearing the durable cart.
  await page.evaluate(({key,pending})=>{const state=JSON.parse(localStorage.getItem(key)!);localStorage.setItem(key,JSON.stringify(state));localStorage.setItem('pikas:pos-cart:v1',pending!)},{key,pending});await page.reload();await expect(page.getByRole('heading',{name:'Compra completada'})).toBeVisible();const after=await data(page);expect(after.purchases).toHaveLength(1);expect(after.students[0].balance).toBe(before.students[0].balance);expect(after.students[0].spentToday).toBe(before.students[0].spentToday);expect(after.students[0].dailyLimitEnabled).not.toBe(false);
});
