import { test, expect, type Page, type BrowserContext } from '@playwright/test';
import { demoKey, invoke, snapshot } from './helpers';
async function login(page: Page, context: BrowserContext, role = 'cafeteria_admin') {
  const admin = role.endsWith('_admin');
  await context.request.post(admin ? '/api/auth/admin-login' : '/api/auth/login', { form: admin ? { identifier: role === 'school_admin' ? 'admin.escuela@demo.pikas.do' : 'admin.cafeteria@demo.pikas.do', password: 'pikas-demo' } : { role: 'pos', identifier: 'cafeteria@demo.pikas.do', password: 'pikas-demo' } });
  await page.goto(admin ? role === 'school_admin' ? '/admin/escuela' : '/admin/cafeteria/personal' : '/pos');
  if (role === 'cafeteria_admin') await expect(page.getByRole('button', { name: 'Agregar empleado' })).toBeEnabled();
}
async function edit(page: Page, name: string, changes: { name?: string; status?: string; role?: string; allowed?: boolean }) {
  await page.getByRole('button', { name: `Editar ${name}`, exact: true }).click();
  if (changes.name) await page.getByLabel('Nombre', { exact: true }).fill(changes.name);
  if (changes.status) await page.getByRole('combobox', { name: 'Estado', exact: true }).selectOption(changes.status);
  if (changes.role) await page.getByRole('combobox', { name: 'Rol POS', exact: true }).selectOption(changes.role);
  if (changes.allowed !== undefined) await page.getByRole('checkbox', { name: 'Caja 1', exact: true }).setChecked(changes.allowed);
  await page.getByRole('button', { name: 'Guardar empleado' }).click();
  await expect(page.getByRole('region', { name: 'Editar empleado POS' })).toBeHidden();
}
const sale = (page: Page, key: string) => invoke(page, 'checkoutPos', [null, [{ itemId: 'menu-pasta', quantity: 1 }], key, 'cash', 18000, true]);
test('Personal POS creates, edits, filters and persists scoped employees with audit only', async ({ page, context }) => {
  test.setTimeout(90000); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await login(page, context);
  await expect(page.getByRole('article')).toHaveCount(3);
  await expect(page.getByRole('link', { name: /Escuelas conectadas/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Agregar empleado' }).click();
  await page.getByLabel('Nombre', { exact: true }).fill('Ana Operaciones');
  await page.getByLabel('Correo', { exact: true }).fill('ana@demo.test');
  await page.getByRole('combobox', { name: 'Rol POS', exact: true }).selectOption('supervisor');
  await page.getByRole('checkbox', { name: 'Caja 1', exact: true }).check();
  await expect(page.getByRole('region', { name: 'Nuevo empleado POS' })).toContainText('No concede administración');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `/tmp/pikas-personal-editor-${test.info().project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Guardar empleado' }).click();
  await expect(page.getByRole('article', { name: 'Ana Operaciones' })).toBeVisible();
  let state = await snapshot(page); const employee = state.administration.users.find((u: { email: string }) => u.email === 'ana@demo.test');
  expect(employee).toMatchObject({ role: 'pos_operator', posRole: 'supervisor', allowedRegisterIds: ['caja-1'], operationalScope: { organizationId: 'cafeteria-demo', locationId: 'principal' } });
  expect(state.administration.memberships.find((m: { userId: string }) => m.userId === employee.id)).toMatchObject({ role: 'pos_operator', authorityScope: { kind: 'cafeteria', organizationId: 'cafeteria-demo', locationId: 'principal' } });
  expect(state.administration.audit[0]).toMatchObject({ actorId: 'ca-1', targetId: employee.id, action: 'Empleado POS creado' });
  const before = state;
  await page.getByLabel('Buscar empleados').fill(employee.id);
  await expect(page.getByRole('article')).toHaveCount(1);
  await edit(page, 'Ana Operaciones', { name: 'Ana Renombrada', role: 'cashier', status: 'suspended', allowed: false });
  await page.getByLabel('Filtrar por rol').selectOption('supervisor'); await expect(page.getByRole('article')).toHaveCount(0);
  await page.getByLabel('Filtrar por rol').selectOption('cashier');
  await page.getByLabel('Filtrar por estado').selectOption('suspended'); await expect(page.getByRole('article')).toHaveCount(1);
  await edit(page, 'Ana Renombrada', { status: 'inactive' });
  await page.getByLabel('Filtrar por estado').selectOption('inactive');
  await edit(page, 'Ana Renombrada', { status: 'active', allowed: true });
  await page.getByLabel('Filtrar por estado').selectOption('active');
  await page.reload(); await expect(page.getByRole('article', { name: 'Ana Renombrada' })).toBeVisible();
  state = await snapshot(page);
  expect(state.administration.users.find((u: { id: string }) => u.id === employee.id)).toMatchObject({ id: employee.id, name: 'Ana Renombrada', status: 'active', posRole: 'cashier' });
  for (const field of ['purchases', 'events', 'students', 'transactions', 'registerSessions', 'menuItems', 'cafeteriaOperations']) expect(state[field]).toEqual(before[field]);
  const changes = state.administration.audit.filter((a: { targetId?: string }) => a.targetId === employee.id);
  expect(changes.every((a: { actorId: string }) => a.actorId === 'ca-1')).toBe(true);
  expect(changes.map((a: { action: string }) => a.action)).toEqual(expect.arrayContaining(['Identidad POS actualizada', 'Rol POS actualizado', 'Acceso a cajas actualizado', 'Empleado POS activado', 'Empleado POS suspendido', 'Empleado POS desactivado']));
  await page.screenshot({ path: `/tmp/pikas-personal-${test.info().project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/admin/cafeteria/escuelas'); await expect(page).toHaveURL(/\/admin\/cafeteria$/);
  expect(errors).toEqual([]);
});
test('suspension and revoked register access block new operations but preserve owner reconciliation and history', async ({ page, context }) => {
  test.setTimeout(90000);
  await login(page, context, 'pos'); expect((await invoke(page, 'openRegister', [0, 'employee-open'])).ok).toBe(true);
  expect((await sale(page, 'before-suspension')).ok).toBe(true);
  const before = await snapshot(page), original = before.registerSessions[0];
  await login(page, context); await edit(page, 'Caja Demo', { name: 'Operador Renombrado', role: 'supervisor', status: 'suspended', allowed: false });
  const changed = await snapshot(page); expect(changed.purchases).toEqual(before.purchases); expect(changed.registerSessions).toEqual(before.registerSessions);
  await login(page, context, 'pos');
  await expect(page.getByRole('heading', { name: 'Acceso de caja suspendido' })).toBeVisible();
  expect((await sale(page, 'suspended-sale')).ok).toBe(false);
  expect((await invoke(page, 'openRegister', [0, 'suspended-open'])).ok).toBe(false);
  expect((await invoke(page, 'replenishPos', ['sofia', 100, 'suspended-topup'])).ok).toBe(false);
  await page.getByRole('link', { name: 'Conciliar y cerrar mi caja' }).click();
  await expect(page.getByRole('region', { name: 'Resumen de sesión' })).toContainText('Caja Demo');
  await page.getByLabel('Efectivo contado (RD$)').fill('180');
  await page.getByRole('button', { name: 'Revisar cierre' }).click();
  page.once('dialog', d => d.accept()); await page.getByRole('button', { name: 'Confirmar cierre' }).click();
  await expect(page.getByRole('heading', { name: 'Cerrar caja', exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Abrir caja', exact: true })).toHaveCount(0);
  let after = await snapshot(page); expect(after.registerSessions[0]).toMatchObject({ id: original.id, status: 'closed', cashierId: 'pos-1', cashierName: 'Caja Demo', expectedCashMinor: 18000, differenceMinor: 0 });
  expect(after.purchases).toEqual(before.purchases); expect(after.events).toEqual(before.events);
  await login(page, context); await edit(page, 'Operador Renombrado', { status: 'active' });
  await login(page, context, 'pos'); expect((await invoke(page, 'openRegister', [0, 'unauthorized-register'])).ok).toBe(false);
  await login(page, context); await edit(page, 'Operador Renombrado', { allowed: true });
  await login(page, context, 'pos'); expect((await invoke(page, 'openRegister', [0, 'supervisor-open'])).ok).toBe(true);
  expect((await sale(page, 'supervisor-sale')).ok).toBe(true);
  after = await snapshot(page); expect(after.purchases[0]).toMatchObject({ cashierId: 'pos-1', employeeLabel: 'Operador Renombrado' });
  expect((await invoke(page, 'adminSetUserStatus', ['pos-2', 'active'])).ok).toBe(false);
  await page.goto('/admin/cafeteria/personal'); await expect(page).not.toHaveURL(/\/personal$/);
});
test('management rejects School/POS crossover, stale updates and scope mismatches without financial writes', async ({ page, context }) => {
  test.setTimeout(90000); await login(page, context); await edit(page, 'Caja Demo', {});
  let state = await snapshot(page);
  const user = state.administration.users.find((u: { id: string }) => u.id === 'pos-1');
  const draft = { id: user.id, name: user.name, email: user.email, posRole: user.posRole, status: user.status, allowedRegisterIds: user.allowedRegisterIds };
  expect((await invoke(page, 'adminSavePosEmployee', [{ ...draft, email: 'admin.cafeteria@demo.pikas.do' }, draft])).ok).toBe(false);
  expect((await invoke(page, 'adminSavePosEmployee', [{ ...draft, name: 'Fresh' }, draft])).ok).toBe(true);
  expect((await invoke(page, 'adminSavePosEmployee', [{ ...draft, name: 'Stale' }, draft])).ok).toBe(false);
  expect((await invoke(page, 'adminUpdateStudent', [state.students[0]])).ok).toBe(false);
  expect((await invoke(page, 'adminSetPartnership', ['partner-active', 'pending'])).ok).toBe(false);
  await login(page, context, 'school_admin');
  expect((await invoke(page, 'adminSavePosEmployee', [{ ...draft, id: 'school-created' }])).ok).toBe(false);
  expect((await invoke(page, 'adminSetUserStatus', ['pos-1', 'active'])).ok).toBe(false);
  await login(page, context); state = await snapshot(page);
  state.administration.memberships.find((m: { userId: string }) => m.userId === 'ca-1').authorityScope.locationId = 'foreign';
  await page.evaluate(({ key, state }) => { localStorage.setItem(key, JSON.stringify(state)); window.dispatchEvent(new StorageEvent('storage', { key })); }, { key: demoKey, state });
  await expect(page.getByRole('alert').filter({ hasText: 'No tienes acceso al personal' })).toBeVisible();
  await expect(page.getByRole('article')).toHaveCount(0);
  expect((await invoke(page, 'adminSavePosEmployee', [{ ...draft, id: 'foreign-created' }])).ok).toBe(false);
  expect((await snapshot(page)).events).toEqual(state.events);
});
test('revoking register assignment on an active employee preserves only owned closure', async ({ page, context }) => {
  test.setTimeout(90000); await login(page, context, 'pos');
  expect((await invoke(page, 'openRegister', [0, 'revoked-open'])).ok).toBe(true);
  await login(page, context); await edit(page, 'Caja Demo', { allowed: false });
  await login(page, context, 'pos'); expect((await sale(page, 'revoked-sale')).ok).toBe(false);
  await page.goto('/pos/caja'); await page.getByLabel('Efectivo contado (RD$)').fill('0');
  await page.getByRole('button', { name: 'Revisar cierre' }).click(); page.once('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Confirmar cierre' }).click();
  await expect(page.getByRole('heading', { name: 'Cerrar caja', exact: true })).toHaveCount(0);
  expect((await invoke(page, 'openRegister', [0, 'revoked-reopen'])).ok).toBe(false);
  expect((await snapshot(page)).registerSessions[0].status).toBe('closed');
});
