import { openDemoRegister } from './helpers';
import { test, expect, type Page } from '@playwright/test';
import { confirmSale, invoke, snapshot } from './helpers';
async function admin(page: Page) {
  await page.goto('/admin/login');
  await page.getByLabel('Correo demo').filter({ visible: true }).fill('admin.cafeteria@demo.pikas.do');
  await page.getByRole('button', { name: 'Entrar a administración' }).click();
  await page.goto('/admin/cafeteria/productos');
  await expect(page.getByRole('button', { name: 'Crear producto', exact: true })).toBeEnabled();
}
async function pos(page: Page) {
  await page.goto('/login');
  await page.getByRole('tab', { name: 'Cafetería' }).click();
  await page.getByRole('button', { name: /Entrar como cafetería/ }).click(); await openDemoRegister(page);
  await page.getByRole('button', { name: 'No usuario', exact: true }).click();
}
test('create, validate, edit and filter products with persistent independent statuses', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await admin(page);
  await page.getByRole('button', { name: 'Crear producto', exact: true }).click();
  await page.getByLabel('Nombre', { exact: true }).fill('Fruta fresca');
  await page.getByLabel('Categoría', { exact: true }).fill('Frutas');
  await page.getByLabel('Precio (RD$)', { exact: true }).fill('-1');
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Precio no válido' })).toContainText('Precio no válido');
  await page.getByLabel('Precio (RD$)', { exact: true }).fill('0');
  await page.getByLabel('Ingredientes', { exact: true }).fill('Manzana\nPera');
  await page.getByLabel('Alérgenos', { exact: true }).fill('Gluten');
  await page.getByLabel('Etiquetas alimentarias', { exact: true }).fill('Vegetariano');
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('status')).toContainText('Producto creado');
  await page.getByLabel('Buscar productos').fill('fruta');
  await expect(page.getByRole('article')).toHaveCount(1);
  await page.getByLabel('Categoría', { exact: true }).selectOption('Frutas');
  await page.getByRole('button', { name: 'Editar Fruta fresca' }).click();
  await expect(page.getByLabel('Alérgenos', { exact: true })).toHaveValue('Gluten');
  await page.getByLabel('Precio (RD$)', { exact: true }).fill('95.00');
  await page.getByRole('checkbox', { name: /^Activo/ }).uncheck();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('status')).toContainText('actualizado');
  await page.getByLabel('Estado', { exact: true }).selectOption('inactive');
  await expect(page.getByRole('article')).toContainText('Inactivo');
  await page.getByRole('button', { name: 'Editar Fruta fresca' }).click();
  await page.getByRole('checkbox', { name: /^Activo/ }).check();
  await page.getByRole('checkbox', { name: /^Disponible/ }).uncheck();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('status')).toContainText('actualizado');
  await page.reload();
  await page.getByLabel('Estado', { exact: true }).selectOption('unavailable');
  await expect(page.getByRole('article').filter({ hasText: 'Fruta fresca' })).toContainText('No disponible');
  const state = await snapshot(page), item = state.menuItems.find((p: { name: string }) => p.name === 'Fruta fresca');
  expect(item).toMatchObject({ active: true, available: false, priceMinor: 9500, allergens: ['Gluten'], ingredients: ['Manzana', 'Pera'], restrictionTags: ['Vegetariano'] });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await page.screenshot({ path: `/tmp/pikas-products-${test.info().project.name}.png`, fullPage: true });
});
test('product edits reach POS while completed snapshots remain unchanged', async ({ page }) => {
  test.setTimeout(90000);
  await pos(page);
  await page.getByRole('article').filter({ hasText: 'Pasta con pollo' }).getByRole('button', { name: 'Añadir al carrito' }).click();
  await page.getByRole('button', { name: 'Continuar al pago' }).click();
  await page.getByRole('button', { name: 'Monto exacto' }).click();
  await confirmSale(page);
  const before = (await snapshot(page)).purchases;
  await admin(page);
  await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click();
  await page.getByLabel('Precio (RD$)', { exact: true }).fill('195');
  await page.getByRole('button', { name: 'Quitar imagen' }).click();
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('status')).toContainText('actualizado');
  await page.reload();
  const saved = await snapshot(page);
  expect(saved.purchases).toEqual(before);
  expect(saved.menuItems.find((p: { id: string }) => p.id === 'menu-pasta').imageUrl).toBeNull();
  await pos(page);
  const pasta = page.getByRole('article').filter({ hasText: 'Pasta con pollo' });
  await expect(pasta).toContainText('195.00');
  await expect(pasta.getByRole('button', { name: 'Añadir al carrito' })).toBeEnabled();
  await admin(page);
  await page.getByRole('button', { name: 'Editar Pasta con pollo' }).click();
  await page.getByRole('checkbox', { name: /^Activo/ }).uncheck();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: /Crear producto|Guardar cambios/ }).click();
  await expect(page.getByRole('status')).toContainText('actualizado');
  await pos(page);
  await expect(pasta).toHaveCount(0);
  expect((await snapshot(page)).purchases).toEqual(before);
});
test('mutation boundary rejects invalid prices and stale writes; same-origin catalog updates propagate', async ({ page }) => {
  test.setTimeout(90000);
  await admin(page);
  const second = await page.context().newPage(); await second.goto('/admin/cafeteria/productos');
  await expect(second.getByRole('button', { name: 'Crear producto', exact: true })).toBeEnabled();
  // First valid write persists the initial demo snapshot.
  const first = await invoke(page, 'adminAddMenu', [{ id: 'test-product', name: 'Prueba compartida', description: '', category: 'Pruebas', priceMinor: 0, available: true, active: true, ingredients: [], allergens: ['Gluten'], restrictionTags: [], imageUrl: null }]);
  expect(first.ok).toBe(true);
  await expect(second.getByRole('button', { name: 'Editar Prueba compartida' })).toBeVisible();
  const original = (await snapshot(page)).menuItems.find((p: { id: string }) => p.id === 'test-product');
  expect((await invoke(page, 'adminUpdateMenu', [{ ...original, priceMinor: -1 }])).ok).toBe(false);
  expect((await invoke(page, 'adminUpdateMenu', [{ ...original, priceMinor: 19500 }, original])).ok).toBe(true);
  expect((await invoke(second, 'adminUpdateMenu', [{ ...original, name: 'Viejo' }, original])).ok).toBe(false);
  await expect(second.getByRole('article').filter({ hasText: 'Prueba compartida' })).toContainText('195.00');
  expect((await snapshot(page)).menuItems.find((p: { id: string }) => p.id === original.id).allergens).toEqual(['Gluten']);
  await second.close();
});
