"use client";
import { useState } from "react";
import type { MenuItem, Preorder, Student, StudentControls, Transaction, Wallet } from "@pikas/shared-types";
import { Avatar, Button, DemoBadge, EmptyState, MockDataNotice } from "@pikas/ui";
type View="inicio"|"menu"|"gastos"|"perfil";
const money=(n:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP",maximumFractionDigits:0}).format(n);
export default function StudentPortal({student,wallet,controls,transactions,menu,preorders}:{student:Student;wallet:Wallet;controls:StudentControls;transactions:Transaction[];menu:MenuItem[];preorders:Preorder[]}){
 const [view,setView]=useState<View>("inicio"),[orders,setOrders]=useState(preorders.map(x=>x.menuItemId)),[budget,setBudget]=useState(600),[editing,setEditing]=useState(false),[notice,setNotice]=useState("");
 const remaining=Math.max(0,wallet.dailyLimit-wallet.spentToday), entertainmentSpent=transactions.filter(x=>x.category==="Entretenimiento").reduce((n,x)=>n+Math.abs(x.amount),0),budgetPercent=Math.min(100,Math.round(entertainmentSpent/Math.max(1,budget)*100));
 function preorder(item:MenuItem){if(item.allergens.some(a=>controls.allergies.includes(a))){setNotice(`No se puede preordenar: ${item.name} contiene ${item.allergens.join(", ")}.`);return}setOrders(old=>old.includes(item.id)?old:[...old,item.id]);setNotice(`${item.name} quedó preordenado en esta sesión demo.`)}
 const nav:[View,string,string][]=[["inicio","⌂","Inicio"],["menu","🍽️","Colegio"],["gastos","◔","Gastos"],["perfil","☺","Perfil"]];
 return <div className="mx-auto min-h-screen max-w-5xl pb-28"><MockDataNotice/><header className="flex items-center justify-between px-5 py-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-violet-600 text-xl font-black text-white">P</span><div><p className="text-xs font-bold text-violet-600">PIKAS STUDENT</p><strong>Hola, {student.name.split(" ")[0]}</strong></div></div><Avatar name={student.name}/></header>
 <main className="px-4 md:px-6">{notice&&<div role="status" className="mb-4 flex justify-between rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-900">{notice}<button onClick={()=>setNotice("")} aria-label="Cerrar">✕</button></div>}
 {view==="inicio"&&<><section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-violet-900 via-violet-600 to-violet-400 p-6 text-white shadow-card"><div className="flex justify-between"><div><span className="text-sm text-violet-100">Saldo disponible</span><p className="mt-1 text-4xl font-black">{money(wallet.availableBalance)}</p></div><DemoBadge/></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3"><small>Disponible hoy</small><strong className="block text-xl">{money(remaining)}</strong></div><div className="rounded-2xl bg-white/10 p-3"><small>Límite diario</small><strong className="block text-xl">{money(wallet.dailyLimit)}</strong></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{width:`${Math.min(100,wallet.spentToday/wallet.dailyLimit*100)}%`}}/></div></section>
 <section className="mt-5 grid gap-5 md:grid-cols-[1.2fr_1fr]"><div className="card p-5"><div className="flex items-start justify-between gap-3"><div><span className="label">Mi identificación</span><h1 className="mt-2 text-xl font-black">{student.name}</h1><p className="text-sm text-slate-500">Instituto Nueva Generación · {student.grade}</p><span className="mt-3 inline-block rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">ID {student.studentCode}</span></div><FakeQr/></div></div><Transactions transactions={transactions.slice(0,3)}/></section></>}
 {view==="menu"&&<section><h1 className="text-3xl font-black">Menú del colegio</h1><p className="text-slate-500">Preordena sin filas. No se realiza un cobro real.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{menu.map(item=><article className="card p-5" key={item.id}><div className="flex gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-amber-50 text-3xl">{item.emoji}</span><div className="flex-1"><h2 className="font-black">{item.name}</h2><p className="text-sm text-slate-500">{item.availableOn}</p><strong className="text-violet-700">{money(item.price)}</strong></div></div><p className="mt-4 text-sm text-slate-600">{item.description}{item.allergens.length?` · Contiene ${item.allergens.join(", ")}`:""}</p><Button disabled={orders.includes(item.id)} className="mt-4 w-full bg-violet-600 hover:bg-violet-700 focus:ring-violet-200" onClick={()=>preorder(item)}>{orders.includes(item.id)?"Preorden demo programada":"Preordenar (demo)"}</Button></article>)}</div></section>}
 {view==="gastos"&&<section><h1 className="text-3xl font-black">Mis gastos</h1><div className="mt-5 grid gap-5 md:grid-cols-[1fr_1.4fr]"><div className="card p-6"><span className="label">Presupuesto personal</span><h2 className="mt-2 text-xl font-black">Plan de entretenimiento</h2><p className="mt-4 text-3xl font-black text-violet-700">{money(budget)}</p><p className="text-sm text-slate-500">Usado: {money(entertainmentSpent)}</p><div className="my-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-600" style={{width:`${budgetPercent}%`}}/></div><button onClick={()=>setEditing(true)} className="font-bold text-violet-700">Configurar meta</button></div><Transactions transactions={transactions}/></div></section>}
 {view==="perfil"&&<section><h1 className="text-3xl font-black">Mi perfil</h1><div className="card mt-5 p-6"><div className="flex items-center gap-4"><Avatar name={student.name} className="size-16 text-xl"/><div><h2 className="text-xl font-black">{student.name}</h2><p className="text-slate-500">{student.grade} · ID {student.studentCode}</p></div></div><h3 className="mt-7 font-black">Información de cuidado</h3><div className="mt-3 flex flex-wrap gap-2">{controls.allergies.map(x=><span key={x} className="rounded-full bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Alergia: {x}</span>)}<span className="rounded-full bg-violet-50 px-3 py-2 text-sm font-bold text-violet-700">Límite: {money(wallet.dailyLimit)}</span></div><p className="mt-6 text-sm text-slate-500">Los controles los administra tu familia. Habla con tu tutor para solicitar cambios.</p></div></section>}
 </main><nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex max-w-xl justify-around border-t bg-white/95 p-2 backdrop-blur" aria-label="Navegación principal">{nav.map(([id,icon,label])=><button className={`nav-item ${view===id?"nav-item-active":""}`} key={id} onClick={()=>setView(id)}><span className="text-lg">{icon}</span>{label}</button>)}</nav>
 {editing&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/40 sm:place-items-center"><div role="dialog" aria-modal="true" aria-labelledby="budget-title" className="w-full max-w-md rounded-t-3xl bg-white p-6 sm:rounded-3xl"><div className="flex justify-between"><div><DemoBadge/><h2 id="budget-title" className="mt-2 text-xl font-black">Mi presupuesto</h2></div><button onClick={()=>setEditing(false)} aria-label="Cerrar">✕</button></div><label htmlFor="budget" className="label mt-5 block">Meta mensual en RD$</label><input className="field mt-2" id="budget" type="number" value={budget} min="1" onChange={e=>setBudget(Number(e.target.value))}/><Button className="mt-4 w-full bg-violet-600 hover:bg-violet-700" onClick={()=>{setEditing(false);setNotice("Presupuesto actualizado durante esta sesión.")}}>Guardar meta demo</Button></div></div>}
 </div>}
function FakeQr(){return <div className="text-center"><div aria-label="Código visual de demostración, no válido" className="grid size-24 grid-cols-5 gap-1 rounded-xl border-4 border-white bg-white p-2 shadow-lg">{Array.from({length:25},(_,i)=><span key={i} className={`${[0,1,2,4,5,7,8,10,12,14,16,18,20,21,22,24].includes(i)?"bg-slate-950":"bg-white"}`}/>)}</div><strong className="mt-2 block text-[10px] uppercase text-red-600">QR demo · no válido</strong></div>}
function Transactions({transactions}:{transactions:Transaction[]}){return <div className="card p-5"><h2 className="font-black">Movimientos</h2><div className="mt-3 divide-y">{transactions.length?transactions.map(tx=><div className="flex items-center gap-3 py-3" key={tx.id}><span className="grid size-10 place-items-center rounded-xl bg-violet-50">{tx.amount>0?"💰":"🧾"}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{tx.description}</strong><small className="text-slate-500">{tx.category}</small></div><strong className={tx.amount>0?"text-emerald-600":""}>{tx.amount>0?"+":"−"}{money(Math.abs(tx.amount))}</strong></div>):<EmptyState>Aún no tienes movimientos.</EmptyState>}</div></div>}
