"use client";
import { useMemo, useState } from "react";
import type { Parent, Student, StudentControls, Transaction, Wallet } from "@pikas/shared-types";
import { Avatar, Brand, Button, DemoBadge, EmptyState, MockDataNotice } from "@pikas/ui";

type StudentRecord = {student:Student;wallet:Wallet|null;controls:StudentControls|null;transactions:Transaction[]};
type View = "inicio"|"movimientos"|"controles"|"familia";
const money=(value:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP",maximumFractionDigits:0}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("es-DO",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(value));

export default function FamilyPortal({parent,records}:{parent:Parent;records:StudentRecord[]}){
  const [view,setView]=useState<View>("inicio"),[activeId,setActiveId]=useState(records[0]?.student.id??"");
  const [topup,setTopup]=useState(false),[amount,setAmount]=useState(500),[sessionCredits,setSessionCredits]=useState<Record<string,number>>({}),[notice,setNotice]=useState("");
  const current=records.find(item=>item.student.id===activeId)??records[0];
  const balance=(current?.wallet?.availableBalance??0)+(sessionCredits[activeId]??0);
  const allTransactions=useMemo(()=>records.flatMap(item=>item.transactions.map(tx=>({...tx,studentName:item.student.name}))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[records]);
  function addFunds(){if(amount<=0)return;setSessionCredits(old=>({...old,[activeId]:(old[activeId]??0)+amount}));setTopup(false);setNotice(`Recarga demo de ${money(amount)} aplicada durante esta sesión.`)}
  const nav:[View,string,string][]=[["inicio","⌂","Inicio"],["movimientos","↔","Movimientos"],["controles","⚙","Controles"],["familia","☺","Mi familia"]];
  return <div className="min-h-screen md:grid md:grid-cols-[250px_1fr]">
    <MockDataNotice />
    <aside className="hidden min-h-screen bg-gradient-to-b from-blue-900 to-blue-600 p-6 text-white md:block"><Brand/><nav className="mt-10 space-y-2" aria-label="Navegación principal">{nav.map(([id,icon,label])=><button key={id} onClick={()=>setView(id)} className={`nav-item w-full ${view===id?"nav-item-active":""}`}><span>{icon}</span>{label}</button>)}</nav><div className="mt-12 rounded-2xl bg-white/10 p-4 text-sm"><strong>¿Necesitas ayuda?</strong><p className="mt-2 text-blue-100">Este MVP utiliza información simulada.</p></div></aside>
    <div><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b bg-white/95 px-5 backdrop-blur md:px-8"><div><span className="label">Portal de familias</span><p className="font-bold">Hola, {parent.name.split(" ")[0]} 👋</p></div><div className="flex items-center gap-3"><DemoBadge/><Avatar name={parent.name}/></div></header>
      <main className="mx-auto max-w-6xl p-4 pb-28 md:p-8">
        {notice&&<div role="status" className="mb-4 flex items-center justify-between rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{notice}<button aria-label="Cerrar aviso" onClick={()=>setNotice("")}>✕</button></div>}
        <div className="mb-6 flex gap-3 overflow-x-auto pb-2" aria-label="Seleccionar estudiante">{records.map(({student,wallet})=><button key={student.id} onClick={()=>setActiveId(student.id)} className={`flex min-w-56 items-center gap-3 rounded-2xl border-2 bg-white p-3 text-left ${student.id===activeId?"border-blue-600":"border-transparent"}`}><Avatar name={student.name}/><span><strong className="block">{student.name}</strong><small className="text-slate-500">{student.grade} · {money((wallet?.availableBalance??0)+(sessionCredits[student.id]??0))}</small></span></button>)}</div>
        {view==="inicio"&&current&&<><section className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-900 via-blue-600 to-blue-400 p-7 text-white shadow-card"><DemoBadge/><p className="mt-8 text-sm text-blue-100">Saldo disponible de {current.student.name}</p><p className="mt-1 text-4xl font-black">{money(balance)}</p><div className="mt-8 flex items-end justify-between"><div><span className="text-xs text-blue-100">Gastado hoy</span><strong className="block">{money(current.wallet?.spentToday??0)}</strong></div><Button className="bg-white text-blue-800 hover:bg-blue-50" onClick={()=>setTopup(true)}>＋ Recarga demo</Button></div></div><div className="card p-6"><span className="label">Resumen familiar</span><p className="mt-3 text-3xl font-black">{money(records.reduce((sum,item)=>sum+(item.wallet?.availableBalance??0)+(sessionCredits[item.student.id]??0),0))}</p><p className="text-sm text-slate-500">Saldo total entre {records.length} estudiantes</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/3 rounded-full bg-blue-600"/></div></div></section>
          <section className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><TransactionList transactions={current.transactions.slice(0,4)} title="Últimos movimientos"/><div className="card p-5"><div className="flex justify-between"><h2 className="font-black">Controles activos</h2><button className="text-sm font-bold text-blue-700" onClick={()=>setView("controles")}>Editar</button></div><div className="mt-4 flex flex-wrap gap-2">{current.controls?.allergies.map(x=><span key={x} className="rounded-full bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Alergia: {x}</span>)}{current.controls?.blockedProducts.map(x=><span key={x} className="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Bloqueado: {x}</span>)}</div></div></section></>}
        {view==="movimientos"&&<section><h1 className="text-3xl font-black">Movimientos</h1><p className="mb-5 text-slate-500">Actividad de todos los estudiantes vinculados.</p><TransactionList transactions={allTransactions} title="Historial familiar"/></section>}
        {view==="controles"&&current&&(
          <Controls record={current} onSave={()=>setNotice("Controles guardados solo durante esta demostración.")}/>
        )}
        {view==="familia"&&<section><h1 className="text-3xl font-black">Mi familia</h1><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-6"><span className="label">Tutor principal</span><h2 className="mt-3 text-xl font-black">{parent.name}</h2><p className="text-slate-500">{parent.email}</p></div><div className="card p-6"><span className="label">Estudiantes vinculados</span><div className="mt-3 space-y-3">{records.map(({student})=><div key={student.id} className="flex items-center gap-3"><Avatar name={student.name}/><div><strong>{student.name}</strong><p className="text-sm text-slate-500">{student.grade} · Código {student.studentCode}</p></div></div>)}</div></div></div></section>}
      </main>
      <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t bg-white p-2 md:hidden" aria-label="Navegación móvil">{nav.map(([id,icon,label])=><button key={id} onClick={()=>setView(id)} className={`flex flex-col items-center rounded-xl py-2 text-xs font-bold ${view===id?"bg-blue-50 text-blue-700":"text-slate-500"}`}><span className="text-lg">{icon}</span>{label}</button>)}</nav>
    </div>
    {topup&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/45 p-0 sm:place-items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="topup-title"><div className="w-full max-w-md rounded-t-3xl bg-white p-6 sm:rounded-3xl"><div className="flex justify-between"><div><DemoBadge/><h2 id="topup-title" className="mt-2 text-xl font-black">Simular recarga</h2></div><button onClick={()=>setTopup(false)} aria-label="Cerrar">✕</button></div><p className="mt-2 text-sm text-slate-600">No se solicita ni procesa información financiera real.</p><label className="label mt-5 block" htmlFor="amount">Monto en RD$</label><input id="amount" className="field mt-2" min="1" type="number" value={amount} onChange={event=>setAmount(Number(event.target.value))}/><Button className="mt-4 w-full" onClick={addFunds}>Aplicar recarga demo</Button></div></div>}
  </div>
}
function TransactionList({transactions,title}:{transactions:(Transaction&{studentName?:string})[];title:string}){return <div className="card p-5"><h2 className="font-black">{title}</h2><div className="mt-3 divide-y">{transactions.length?transactions.map(tx=><div key={tx.id} className="flex items-center gap-3 py-4"><span className="grid size-11 place-items-center rounded-xl bg-slate-100">{tx.amount>0?"💰":"🥪"}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{tx.description}</strong><small className="text-slate-500">{tx.studentName?`${tx.studentName} · `:""}{date(tx.createdAt)}</small></div><strong className={tx.amount>0?"text-emerald-600":"text-slate-900"}>{tx.amount>0?"+":"−"}{money(Math.abs(tx.amount))}</strong></div>):<EmptyState>No hay movimientos para mostrar.</EmptyState>}</div></div>}
function Controls({record,onSave}:{record:StudentRecord;onSave:()=>void}){const [limit,setLimit]=useState(record.wallet?.dailyLimit??0),[transfers,setTransfers]=useState(record.controls?.transfersAllowed??false);return <section><h1 className="text-3xl font-black">Controles y salud</h1><p className="text-slate-500">Configura límites y alertas para {record.student.name}.</p><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-6"><label className="font-bold" htmlFor="limit">Límite diario de compra</label><p className="mb-3 text-sm text-slate-500">Monto máximo que puede gastar por día.</p><input id="limit" className="field" type="number" value={limit} onChange={e=>setLimit(Number(e.target.value))}/><label className="mt-6 flex items-center justify-between font-bold">Permitir transferencias<input type="checkbox" checked={transfers} onChange={e=>setTransfers(e.target.checked)} className="size-5"/></label></div><div className="card p-6"><h2 className="font-bold">Alergias</h2><div className="my-3 flex flex-wrap gap-2">{record.controls?.allergies.length?record.controls.allergies.map(x=><span key={x} className="rounded-full bg-red-50 px-3 py-2 text-sm text-red-700">{x}</span>):<span className="text-sm text-slate-500">Sin alergias registradas</span>}</div><h2 className="mt-5 font-bold">Productos bloqueados</h2><div className="my-3 flex flex-wrap gap-2">{record.controls?.blockedProducts.map(x=><span key={x} className="rounded-full bg-amber-50 px-3 py-2 text-sm text-amber-800">{x}</span>)}</div></div></div><Button className="mt-5" onClick={onSave}>Guardar cambios demo</Button></section>}
