"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {BrandLogo} from "./brand-logo";
import {Home,Users,Utensils,ReceiptText,ShieldCheck,LogOut} from "./icons";
const school=[["/admin/escuela","Resumen",Home],["/admin/escuela/estudiantes","Estudiantes",Users],["/admin/escuela/administradores","Administradores",ShieldCheck],["/admin/escuela/cafeterias","Cafeterías conectadas",Utensils],["/admin/escuela/actividad","Actividad",ReceiptText]] as const;
const cafeteria=[["/admin/cafeteria","Resumen",Home],["/admin/cafeteria/menu","Menú y productos",Utensils],["/admin/cafeteria/personal","Personal de caja",Users],["/admin/cafeteria/escuelas","Escuelas conectadas",ShieldCheck],["/admin/cafeteria/transacciones","Transacciones",ReceiptText]] as const;
export function AdminShell({kind,children}:{kind:"school"|"cafeteria";children:React.ReactNode}){
  const path=usePathname(),items=kind==="school"?school:cafeteria,root=kind==="school"?"/admin/escuela":"/admin/cafeteria";
  const links=(mobile=false)=>items.map(([href,label,Icon])=>{const current=path===href||(href!==root&&path.startsWith(href));return <Link key={href} href={href} aria-current={current?"page":undefined} className={mobile?`flex min-h-16 min-w-0 flex-col items-center justify-center gap-1 rounded-xl px-1 text-[10px] font-bold ${current?(kind==="school"?"bg-blue-50 text-pikas-navy":"bg-teal-50 text-teal-950"):"text-slate-600"}`:`nav-link ${current?"bg-white text-pikas-navy":"text-white/80 hover:bg-white/10"}`}><Icon size={18}/><span className={mobile?"max-w-full truncate":undefined}>{mobile?label.replace(" conectadas",""):label}</span></Link>});
  return <div className="min-h-screen bg-slate-50 md:grid md:grid-cols-[250px_minmax(0,1fr)]" data-testid="admin-shell"><aside className={`sticky top-0 hidden h-screen flex-col p-5 text-white md:flex ${kind==="school"?"bg-pikas-navy":"bg-teal-950"}`}><Link href={root} className="flex min-h-11 items-center"><span className="rounded-xl bg-white p-1"><BrandLogo compact className="size-9"/></span><span className="ml-2 font-black">PIKAS Admin</span></Link><p className="mt-2 text-xs font-bold uppercase tracking-widest text-white/70">{kind==="school"?"Administración escolar":"Administración de cafetería"}</p><nav className="mt-8 space-y-1" aria-label="Administración">{links()}</nav><form action="/api/auth/logout" method="post" className="mt-auto"><button className="nav-link w-full text-white/80"><LogOut size={18}/>Cerrar sesión</button></form></aside><div className="min-w-0"><header className={`sticky top-0 z-30 flex min-h-14 items-center justify-between gap-2 border-b bg-white/95 px-4 md:px-6 ${kind==="school"?"border-b-blue-100":"border-b-teal-200"}`}><Link href={root} className="font-black text-pikas-navy md:hidden">PIKAS Admin</Link><div className="min-w-0"><span className="label">Organización</span><p className="truncate text-sm font-bold">{kind==="school"?"Instituto Nueva Generación":"Cafetería PIKAS Central"}</p></div><form action="/api/auth/logout" method="post" className="md:hidden"><button aria-label="Cerrar sesión" className="grid size-11 place-items-center rounded-xl text-slate-600"><LogOut size={18}/></button></form></header><main className="app-main mx-auto max-w-7xl p-4 sm:p-5 md:p-6">{children}</main><nav className="mobile-nav fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t bg-white/95 p-1 md:hidden" aria-label="Administración móvil">{links(true)}</nav></div></div>;
}
