'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { CafeteriaRead, Operation } from '../lib/cafeteria/contracts';
import { useCafeteriaMutation } from './connected-cafeteria-provider';
import { CafeteriaProductsEditor } from './cafeteria-products-editor';
import { CafeteriaMenusEditor } from './cafeteria-menus-editor';
export type CafeteriaSection='summary'|'products'|'menus'|'shifts'|'staff'|'registers'|'settings'|'transactions'|'schools';
const statusLabel=(s:string)=>({active:'Activo',inactive:'Inactivo',suspended:'Suspendido',archived:'Archivado',pending:'Pendiente',accepted:'Completado',expired:'Vencido',revoked:'Revocado'})[s]??s;
const roleLabel=(s:string)=>s==='pos_supervisor'?'Supervisor':'Cajero';
const value=(data:FormData,key:string)=>String(data.get(key)??'').trim();
function Input({label,name,initial='',type='text',maxLength=120,readOnly=false}:{label:string;name:string;initial?:string;type?:string;maxLength?:number;readOnly?:boolean}) {
 return <label className="block font-bold">{label}<input className="field mt-1" required name={name} type={type} maxLength={maxLength} defaultValue={initial} readOnly={readOnly}/></label>;
}
function CommandForm({operation,payload,label,children,confirmation,onSuccess}:{operation:Operation;payload:(data:FormData)=>unknown;label:string;children?:React.ReactNode;confirmation?:string;onSuccess?:()=>void}) {
 const execute=useCafeteriaMutation();
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(confirmation&&!window.confirm(confirmation))return;const result=await execute(operation,payload(new FormData(e.currentTarget)));if(result.ok)onSuccess?.();}}>{children}<button className="btn" type="submit">{label}</button></form>;
}
function Staff({data}:{data:CafeteriaRead}) {
 const [query,setQuery]=useState(''),[role,setRole]=useState(''),[status,setStatus]=useState(''),[editing,setEditing]=useState<string|null>(null);
 const staff=data.staff.filter(m=>(!role||m.role===role)&&(!status||m.status===status)&&m.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><p className="label">Administración de cafetería</p><h1 className="text-3xl font-black">Personal POS</h1><p className="mt-2 text-slate-600">Identidad, estado y acceso a cajas de los empleados.</p></div><button className="btn" onClick={()=>setEditing(editing==='new'?null:'new')}>Agregar empleado</button></header>
 <p className="rounded-xl bg-amber-50 p-3 text-sm">No se envía un correo ni se crean contraseñas. Prepara el acceso; la persona debe registrarse y confirmar su correo antes de concederlo. Supervisor es un rol operativo y no concede administración.</p>
 {editing==='new'&&<section className="card p-5"><h2 className="mb-4 text-xl font-black">Nuevo empleado POS</h2><CommandForm operation="staff_prepare" label="Preparar acceso pendiente" payload={d=>({email:value(d,'email'),role:value(d,'role')})} onSuccess={()=>setEditing(null)}><Input label="Correo" name="email" type="email" maxLength={254}/><label className="block font-bold">Rol POS<select className="field mt-1" name="role"><option value="pos_cashier">Cajero</option><option value="pos_supervisor">Supervisor</option></select></label></CommandForm><button className="btn-secondary mt-3" onClick={()=>setEditing(null)}>Cancelar</button></section>}
 <div className="grid gap-3 sm:grid-cols-3"><label className="font-bold">Buscar empleados<input className="field mt-1" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre"/></label><label className="font-bold">Filtrar por rol<select className="field mt-1" value={role} onChange={e=>setRole(e.target.value)}><option value="">Todos los roles</option><option value="pos_cashier">Cajero</option><option value="pos_supervisor">Supervisor</option></select></label><label className="font-bold">Filtrar por estado<select className="field mt-1" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{['active','suspended','inactive'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label></div>
 <p className="text-sm text-slate-500">{staff.length} de {data.staff.length} empleados</p>
 {staff.map(m=><article className="card space-y-3 p-4" key={m.id}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-black">{m.name}</h2><button className="btn-secondary" aria-label={`Editar ${m.name}`} onClick={()=>setEditing(editing===m.id?null:m.id)}>Editar</button></div><p>{roleLabel(m.role)} · {statusLabel(m.status)}</p><p className="text-sm">Cajas: {data.assignments.filter(a=>a.membership_id===m.id&&a.status==='active').map(a=>data.registers.find(r=>r.id===a.register_id)?.name).join(', ')||'Sin asignación'}</p><p className="text-sm">{m.open?'Sesión abierta; suspender o retirar asignaciones bloquea nuevas operaciones y conserva el cierre propio.':'Sin sesión abierta'}</p>{editing===m.id&&<CommandForm operation="staff_status" label="Guardar estado" confirmation="¿Confirmar el cambio de acceso POS?" payload={d=>({membership_id:m.id,status:value(d,'status')})} onSuccess={()=>setEditing(null)}><label className="block font-bold">Estado<select className="field mt-1" name="status" defaultValue={m.status}>{['active','suspended','inactive'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><p className="text-sm">Las cajas se asignan en Cajas. El rol concedido y la identidad se conservan.</p></CommandForm>}</article>)}
 {!staff.length&&<p className="card p-5">No hay empleados que coincidan.</p>}
 <h2 className="text-xl font-black">Accesos preparados</h2>{data.invitations.map(i=><article className="card space-y-3 p-4" key={i.id}><p className="break-all font-bold">{i.email}</p><p>{roleLabel(i.role)} · {statusLabel(i.status)} · Vence {new Date(i.expires_at).toLocaleDateString('es-DO',{timeZone:'UTC'})}</p>{i.status==='pending'&&<CommandForm operation="staff_complete" label="Confirmar identidad y conceder acceso POS" confirmation="¿Conceder acceso operativo exclusivamente a esta cafetería?" payload={d=>({invitation_id:i.id,display_name:value(d,'display_name')})}><Input label="Nombre completo" name="display_name" maxLength={200}/></CommandForm>}</article>)}{!data.invitations.length&&<p className="card p-5">No hay accesos preparados.</p>}
 </div>;
}
function Registers({data}:{data:CafeteriaRead}) {
 const [editing,setEditing]=useState<string|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState('');
 const registers=data.registers.filter(r=>(!status||r.status===status)&&`${r.name} ${r.code}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const register=data.registers.find(r=>r.id===editing);
 return <div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><p className="label">Administración de cafetería</p><h1 className="text-3xl font-black">Cajas</h1><p className="mt-2 text-slate-600">Configuración, estado operativo y personal autorizado.</p></div><button className="btn" onClick={()=>setEditing('new')}>Crear caja</button></header>
 {editing&&<section className="card p-5"><h2 className="mb-4 text-xl font-black">{register?'Editar caja':'Crear caja'}</h2><CommandForm operation="register_save" label="Guardar caja" confirmation={register?'¿Confirmar los cambios de caja?':undefined} onSuccess={()=>setEditing(null)} payload={d=>({id:register?.id??crypto.randomUUID(),version:register?.version??null,code:value(d,'code'),name:value(d,'name'),status:register?value(d,'status'):'active'})}><div className="grid gap-4 sm:grid-cols-2"><Input label="Nombre de caja" name="name" initial={register?.name}/><Input label="Código de caja" name="code" maxLength={32} initial={register?.code} readOnly={register?.has_history}/></div>{register&&<label className="block font-bold">Estado<select className="field mt-1" name="status" defaultValue={register.status}><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label>}<p className="text-sm">Una sesión abierta bloquea cambios de configuración. El código se conserva después del primer uso.</p></CommandForm><button className="btn-secondary mt-3" onClick={()=>setEditing(null)}>Cancelar</button></section>}
 <div className="grid gap-3 sm:grid-cols-2"><label className="font-bold">Buscar cajas<input className="field mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o código"/></label><label className="font-bold">Estado<select className="field mt-1" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label></div>
 {registers.map(r=><article className="card space-y-4 p-5" key={r.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-black">{r.name}</h2><p>{r.code} · {statusLabel(r.status)} · {r.open?'Sesión abierta':'Sin sesión abierta'}</p></div><button className="btn-secondary" disabled={r.open} onClick={()=>setEditing(r.id)}>Editar</button></div>
 <details><summary className="cursor-pointer font-bold">Personal autorizado</summary><div className="mt-4 space-y-4">{data.staff.map(m=>{const assignment=data.assignments.find(a=>a.register_id===r.id&&a.membership_id===m.id); const active=assignment?.status==='active';if(!active&&(m.status!=='active'||r.status!=='active'))return null;return <div key={m.id} className="flex flex-wrap items-center justify-between gap-3 border-t pt-3"><p>{m.name} · {roleLabel(m.role)} · {active?'Asignado':'Sin asignación'}</p><CommandForm operation="assignment_save" label={active?'Retirar asignación':'Asignar'} confirmation="¿Confirmar el cambio de acceso a esta caja?" payload={()=>({membership_id:m.id,register_id:r.id,status:active?'inactive':'active',version:assignment?.version??null})}/></div>;})}{!data.staff.length&&<p>No hay personal POS. Prepara su acceso en Personal POS.</p>}</div></details></article>)}{!registers.length&&<p className="card p-5">No hay cajas que coincidan.</p>}
 </div>;
}
function Categories({data}:{data:CafeteriaRead}) {
 return <details className="card mt-5 p-5"><summary className="cursor-pointer text-lg font-black">Categorías</summary><div className="mt-4 space-y-5"><CommandForm operation="category_save" label="Crear categoría" payload={d=>({id:crypto.randomUUID(),version:null,name:value(d,'name'),display_order:0,status:'active'})}><Input label="Nombre de categoría" name="name" maxLength={80}/></CommandForm>{data.categories.map(c=><section className="border-t pt-4" key={c.id}><CommandForm operation="category_save" label="Guardar categoría" confirmation="¿Guardar los cambios de categoría?" payload={d=>({id:c.id,version:c.version,name:value(d,'name'),display_order:Number(value(d,'display_order')),status:value(d,'status')})}><Input label="Nombre de categoría" name="name" initial={c.name} maxLength={80}/><Input label="Orden" name="display_order" initial={String(c.display_order)} type="number"/><label className="block font-bold">Estado<select className="field mt-1" name="status" defaultValue={c.status}><option value="active">Activa</option><option value="archived">Archivada</option></select></label></CommandForm></section>)}</div></details>;
}
export function ConnectedCafeteriaPages({section,data}:{section:CafeteriaSection;data:CafeteriaRead}) {
 const href=(path:string)=>`/admin/cafeteria${path}?cafeteria=${data.scope.cafeteria_id}`;
 if(section==='products')return <><CafeteriaProductsEditor/><Categories data={data}/></>;
 if(section==='menus'||section==='shifts')return <CafeteriaMenusEditor shifts={section==='shifts'}/>;
 if(section==='staff')return <Staff data={data}/>;
 if(section==='registers')return <Registers data={data}/>;
 if(section==='settings')return <><h1 className="text-3xl font-black">Configuración POS</h1><section className="card mt-5 space-y-3 p-5"><h2 className="text-xl font-black">Operación de cafetería</h2><p>{data.scope.cafeteria_name} · {data.scope.school_name} · {data.scope.location_name}</p><p>Moneda del catálogo: {data.settings.currency}</p><CommandForm operation="settings_save" label="Guardar modo de servicio" confirmation="¿Confirmar el modo de servicio? Cambia los productos ofrecidos en POS." payload={d=>({version:data.settings.version,scheduling_enabled:d.has('scheduling_enabled')})}><label className="flex min-h-12 items-center gap-3"><input type="checkbox" name="scheduling_enabled" defaultChecked={data.settings.scheduling_enabled}/>Activar turnos de servicio</label></CommandForm></section><section className="card mt-5 p-5"><h2 className="text-xl font-black">Controles pendientes</h2><p className="mt-2">Preferencias visuales POS, imágenes y etiquetas alimentarias adicionales aún no tienen configuración conectada. Políticas de reembolso, solicitudes familiares y reportes se habilitarán en una fase posterior.</p></section></>;
 if(section==='transactions')return <><h1 className="text-3xl font-black">Transacciones</h1><p className="card mt-5 p-5">El historial y la conciliación estarán disponibles en una fase posterior.</p></>;
 if(section==='schools')return <><h1 className="text-3xl font-black">Escuelas conectadas</h1><p className="card mt-5 p-5">{data.scope.school_name} · {data.scope.location_name}. La escuela administra la compartición y la elegibilidad estudiantil.</p></>;
 return <><header><p className="label">Administración de cafetería</p><h1 className="text-3xl font-black">{data.scope.cafeteria_name}</h1><p className="mt-2 text-slate-600">Estado activo · {data.scope.school_name} · {data.scope.location_name}</p></header><div className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Productos disponibles',data.products.filter(p=>p.active&&p.available).length],['Menús activos',data.menus.filter(m=>m.active).length],['Personal POS activo',data.staff.filter(m=>m.status==='active').length],['Cajas activas',data.registers.filter(r=>r.status==='active').length]].map(([label,count])=><article className="card p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{count}</p></article>)}</div><section className="card mt-5 p-5"><h2 className="text-xl font-black">Menú y operación de hoy</h2><p className="mt-2">{data.settings.scheduling_enabled?'Programación activada: el POS requiere un turno y menú activos.':'Modo manual: catálogo activo y disponible.'} Siempre se requiere personal autorizado, asignación y una sesión de caja abierta.</p><p className="mt-2">Servicio actual: {data.service ? ({manual:"Catálogo manual",active:"Turno activo",no_active_service:"Sin turno activo",invalid_configuration:"Revisar configuración"})[data.service.status] : "No disponible"}{data.service?.menu_name ? ` · ${data.service.menu_name}` : ""}. {data.registers.filter(r=>r.open).length} sesiones de caja abiertas.</p><div className="mt-4 flex flex-wrap gap-2"><Link className="btn" href={href('/productos')}>Administrar productos</Link><Link className="btn-secondary" href={href('/menus/turnos')}>Turnos de servicio</Link><Link className="btn-secondary" href={href('/cajas')}>Administrar cajas</Link></div></section></>;
}
