"use client";
import Link from "next/link";
import { useState } from "react";
import { SchoolCommandForm } from "./school-command-form";
import type { SchoolRead, SchoolSection, SchoolStudent } from "../lib/school/contracts";
const titles: Record<SchoolSection, string> = { summary: "Resumen de la escuela", students: "Estudiantes", administrators: "Administradores", cafeterias: "Cafeterías conectadas", activity: "Actividad" };
const value = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const optional = (data: FormData, key: string) => value(data, key) || null;
const names = (data: FormData) => ({ first_name: value(data, "first_name"), last_name: value(data, "last_name"), student_code: value(data, "student_code") });
const placement = (data: FormData) => ({ location_id: optional(data, "location_id"), starts_on: value(data, "starts_on"), grade: optional(data, "grade"), class: optional(data, "class"), homeroom: optional(data, "homeroom") });
const statusLabel = (status: string) => ({ active: "Activo", suspended: "Suspendido", inactive: "Inactivo", pending: "Pendiente", accepted: "Completado", expired: "Vencido", revoked: "Revocado" })[status] ?? "No disponible";
function Input({ label, name, defaultValue = "", type = "text", required = true, maxLength = 80 }: { label: string; name: string; defaultValue?: string; type?: string; required?: boolean; maxLength?: number }) {
  return <label className="block text-sm font-semibold">{label}<input className="field mt-1 w-full" name={name} type={type} required={required} maxLength={maxLength} defaultValue={defaultValue} /></label>;
}
function Placement({ data, student }: { data: SchoolRead; student?: SchoolStudent }) {
  return <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Campus<select name="location_id" className="field mt-1 w-full" defaultValue={student?.enrollment?.location_id ?? ""}><option value="">Sin campus asignado</option>{data.locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Input label="Fecha efectiva" name="starts_on" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /><Input label="Grado" name="grade" defaultValue={student?.enrollment?.grade ?? ""} required={false} /><Input label="Sección" name="class" defaultValue={student?.enrollment?.class ?? ""} required={false} /><Input label="Aula / grupo" name="homeroom" defaultValue={student?.enrollment?.homeroom ?? ""} required={false} /></div>;
}
function StudentNames({ student }: { student?: SchoolStudent }) { return <div className="grid gap-3 sm:grid-cols-3"><Input label="Nombre" name="first_name" defaultValue={student?.first_name} /><Input label="Apellido" name="last_name" defaultValue={student?.last_name} /><Input label="Código estudiantil" name="student_code" maxLength={64} defaultValue={student?.student_code} /></div>; }
function CsvPreview() {
  const [csv, setCsv] = useState("");
  const lines = csv.trim().split(/\r?\n/);
  const valid = lines[0] === "student_code,first_name,last_name,grade" && lines.slice(1).every(line => line.split(",").length === 4);
  return <details className="card p-4"><summary className="cursor-pointer font-bold">Vista previa CSV</summary><p className="my-3 text-sm text-slate-500">Encabezado: student_code,first_name,last_name,grade. La importación masiva aún no está disponible.</p><textarea className="field min-h-28 w-full" aria-label="CSV para vista previa" maxLength={10000} value={csv} onChange={e => setCsv(e.target.value)} />{csv && <p role="status" className="my-2 text-sm">{valid ? `${Math.max(0, lines.length - 1)} filas en la vista previa. No se han importado.` : "Revisa el encabezado y las cuatro columnas; esta vista no admite comas dentro de campos."}</p>}<button className="btn-secondary" disabled>Importar — no disponible</button></details>;
}
const categories = [["basic_identification", "Identificación básica"], ["student_code", "Código estudiantil"], ["placement", "Grado y campus"], ["dietary_restrictions", "Restricciones alimentarias"]] as const;
export function ConnectedSchoolPages({ section, data, students = [], query = "", status = "" }: { section: SchoolSection; data: SchoolRead; students?: SchoolStudent[]; query?: string; status?: string }) {
  const scope = data.scope;
  const props = { actorId: scope.actor_id, schoolId: scope.school_id };
  const href = (path: string) => `/admin/escuela${path}?school=${scope.school_id}`;
  return <><header><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Administración escolar</p><h1 className="mt-2 text-3xl font-black">{titles[section]}</h1><p className="mt-2 text-sm text-slate-500">{scope.school_name} · Información de tu escuela.</p></header>
  {section === "summary" && data.counts && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Estudiantes", data.counts.students], ["Activos", data.counts.active], ["Suspendidos", data.counts.suspended], ["Cafeterías conectadas", data.counts.cafeterias]].map(([label, count]) => <article key={label} className="card p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{count}</p></article>)}</div><div className="grid gap-4 md:grid-cols-2"><Link className="card p-5 font-bold" href={href("/estudiantes")}>Gestionar estudiantes →</Link><Link className="card p-5 font-bold" href={href("/cafeterias")}>Revisar cafeterías conectadas →</Link></div><p className="text-sm text-slate-500">Los indicadores financieros y la administración de monederos no están disponibles en esta sección.</p></>}
  {section === "students" && <><form method="get" className="flex flex-wrap gap-3"><input name="school" type="hidden" value={scope.school_id} /><input className="field flex-1" name="q" aria-label="Buscar estudiantes por nombre o código" placeholder="Buscar por nombre o código" maxLength={80} defaultValue={query} /><select className="field" name="status" aria-label="Estado del estudiante" defaultValue={status}><option value="">Todos los estados</option>{["active", "suspended", "inactive"].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select><button className="btn-secondary">Buscar</button></form>
  <details className="card p-4"><summary className="cursor-pointer font-bold">Crear y matricular estudiante</summary><div className="mt-4"><SchoolCommandForm {...props} formId="student-create" operation="student_create" label="Crear y matricular" makePayload={data => ({ ...names(data), ...placement(data) })}><StudentNames /><Placement data={data} /><p className="text-sm text-slate-500">No se crea una cuenta de acceso ni se modifica un monedero.</p></SchoolCommandForm></div></details>
  <div className="space-y-3">{students.map(student => <article className="card space-y-3 p-4" key={student.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{student.display_name}</h2><p className="text-sm text-slate-500">Código {student.student_code} · {student.enrollment ? `${student.enrollment.grade || "Sin grado"} · ${data.locations.find(l => l.id === student.enrollment?.location_id)?.name ?? "Sin campus activo"}` : "Sin matrícula activa"}</p></div><span className="chip">{statusLabel(student.status)}</span></div>
    <details><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Editar estudiante</summary><div className="mt-3"><SchoolCommandForm {...props} formId={`student-update:${student.id}`} operation="student_update" label="Guardar información" makePayload={d => ({ student_id: student.id, ...names(d) })}><StudentNames student={student} /></SchoolCommandForm></div></details>
    <details><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Matrícula y campus</summary><div className="mt-3 space-y-4"><SchoolCommandForm {...props} formId={`placement:${student.id}`} operation={student.enrollment ? "student_transfer" : "student_enroll"} label={student.enrollment ? "Transferir / actualizar colocación" : "Matricular"} confirmation="¿Confirmar la nueva matrícula o colocación?" makePayload={d => ({ student_id: student.id, ...placement(d) })}><Placement data={data} student={student} /></SchoolCommandForm>{student.enrollment && <SchoolCommandForm {...props} formId={`withdraw:${student.id}`} operation="student_withdraw" label="Retirar matrícula" confirmation="¿Retirar la matrícula activa? La fecha debe ser posterior al inicio." makePayload={d => ({ student_id: student.id, ends_on: value(d, "ends_on") })}><Input label="Fecha de retiro" name="ends_on" type="date" /></SchoolCommandForm>}</div></details>
    <SchoolCommandForm {...props} formId={`status:${student.id}`} operation="student_status" label="Cambiar estado" confirmation="¿Confirmar el cambio de estado del estudiante?" makePayload={d => ({ student_id: student.id, status: value(d, "status") })}><select name="status" aria-label={`Estado de ${student.display_name}`} className="field" defaultValue={student.status}>{["active", "suspended", "inactive"].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select><p className="text-xs text-slate-500">Para pasar a inactivo, retira primero su matrícula activa.</p></SchoolCommandForm>
  </article>)}</div>{students.length === 0 && <p className="card p-5 text-slate-500">No hay estudiantes para esta búsqueda.</p>}{data.next_cursor && <Link className="btn-secondary inline-flex" href={`${href("/estudiantes")}&q=${encodeURIComponent(query)}&status=${status}&after=${data.next_cursor}`}>Siguiente página</Link>}<CsvPreview /></>}
  {section === "administrators" && <><details className="card p-4"><summary className="cursor-pointer font-bold">Preparar administrador</summary><div className="mt-4"><p className="mb-3 text-sm text-slate-500">Se prepara acceso exclusivamente a esta escuela. No se envía un correo ni se crean contraseñas. La persona debe tener su correo confirmado antes de completar el acceso.</p><SchoolCommandForm {...props} formId="admin-prepare" operation="admin_prepare" label="Preparar acceso pendiente" makePayload={d => ({ email: value(d, "email") })}><Input label="Correo del administrador" name="email" type="email" maxLength={254} /></SchoolCommandForm></div></details>
  <div className="space-y-3">{data.memberships?.map(member => <article className="card p-4" key={member.id}><h2 className="font-bold">{member.display_name}{member.self ? " · Tú" : ""}</h2><p className="my-2 text-sm text-slate-500">{member.role === "account_admin" ? "Administrador de cuenta · Solo lectura aquí" : "Administrador de escuela"} · {statusLabel(member.status)}</p>{member.manageable && <SchoolCommandForm {...props} formId={`admin-status:${member.id}`} operation="admin_status" label={member.status === "active" ? "Suspender acceso" : "Activar acceso"} confirmation="¿Confirmar el cambio de acceso a esta escuela?" makePayload={() => ({ membership_id: member.id, status: member.status === "active" ? "suspended" : "active" })} />}</article>)}</div>
  <h2 className="text-lg font-bold">Accesos preparados</h2>{data.invitations?.map(invite => <article className="card space-y-3 p-4" key={invite.id}><p className="font-semibold">{invite.email}</p><p className="text-sm text-slate-500">{statusLabel(invite.status)} · Vence {new Date(invite.expires_at).toLocaleDateString("es-DO", { timeZone: "UTC" })}</p>{invite.status === "pending" && <SchoolCommandForm {...props} formId={`admin-complete:${invite.id}`} operation="admin_complete" label="Confirmar identidad y conceder acceso" confirmation="¿Conceder administración exclusivamente de esta escuela a la identidad confirmada de este correo?" makePayload={d => ({ invitation_id: invite.id, display_name: value(d, "display_name") })}><Input label="Nombre completo" name="display_name" maxLength={200} /></SchoolCommandForm>}</article>)}{!data.invitations?.length && <p className="card p-5 text-slate-500">No hay accesos preparados.</p>}</>}
  {section === "cafeterias" && <><p className="text-sm text-slate-500">Compartir información no concede permisos para operar una cafetería ni modificar sus productos o cajas.</p>{data.rows?.map(row => "name" in row && <article className="card space-y-4 p-5" key={row.id}><div><h2 className="font-bold">{row.name}</h2><p className="text-sm text-slate-500">{row.location} · {statusLabel(row.status)} · Compartición {row.sharing_status === "active" ? "activa" : "revocada"} · {row.customer_count} clientes activos</p></div><SchoolCommandForm {...props} formId={`sharing:${row.id}`} operation="sharing_set" label="Guardar compartición" confirmation="¿Confirmar los datos compartidos con esta cafetería?" makePayload={d => ({ cafeteria_id: row.id, status: value(d, "status"), categories: d.getAll("categories") })}><select className="field" name="status" aria-label={`Compartición con ${row.name}`} defaultValue={row.sharing_status}><option value="active">Activa</option><option value="revoked">Revocada</option></select><div className="flex flex-wrap gap-4">{categories.map(([key, label]) => <label className="text-sm" key={key}><input type="checkbox" name="categories" value={key} defaultChecked={row.categories.includes(key)} /> {label}</label>)}</div></SchoolCommandForm>
    <details><summary className="cursor-pointer font-semibold">Elegibilidad de estudiantes</summary><div className="mt-3 space-y-3"><p className="text-xs text-slate-500">Selección: hasta 100 estudiantes de esta escuela. La búsqueda permite localizar otros estudiantes. Se muestran hasta 100 relaciones activas.</p><form method="get" className="flex gap-2"><input type="hidden" name="school" value={scope.school_id} /><input className="field" name="q" placeholder="Buscar estudiante" aria-label={`Buscar estudiante para ${row.name}`} maxLength={80} defaultValue={query} /><button className="btn-secondary">Buscar</button></form><SchoolCommandForm {...props} formId={`customer-add:${row.id}`} operation="customer_set" label="Habilitar estudiante" confirmation="¿Habilitar este estudiante para la cafetería? Requiere matrícula y compartición activas." makePayload={d => ({ cafeteria_id: row.id, student_id: value(d, "student_id"), enabled: true })}><select className="field w-full" name="student_id" required aria-label={`Estudiante para ${row.name}`} defaultValue=""><option value="" disabled>Seleccionar estudiante</option>{students.filter(s => s.status === "active" && s.enrollment).map(s => <option key={s.id} value={s.id}>{s.display_name} · {s.student_code}</option>)}</select></SchoolCommandForm>{row.customers.map(customer => <div key={customer.student_id} className="flex flex-wrap items-center justify-between gap-3 border-t pt-3"><p className="text-sm">{customer.display_name} · {statusLabel(customer.status)}</p>{customer.status === "active" && <SchoolCommandForm {...props} formId={`customer-remove:${row.id}:${customer.student_id}`} operation="customer_set" label="Deshabilitar" confirmation="¿Deshabilitar esta relación con la cafetería?" makePayload={() => ({ cafeteria_id: row.id, student_id: customer.student_id, enabled: false })} />}</div>)}</div></details>
  </article>)}{!data.rows?.length && <p className="card p-5 text-slate-500">No hay cafeterías en esta escuela.</p>}</>}
  {section === "activity" && <><p className="text-sm text-slate-500">Últimos 50 eventos de administración escolar. No incluye operaciones financieras ni actividad de plataforma.</p><div className="card divide-y">{data.rows?.map(row => "action" in row && <article className="flex flex-wrap justify-between gap-3 p-4" key={row.id}><div><p className="font-semibold">{activityLabel(row.action, row.target_type)}</p><p className="text-sm text-slate-500">{row.actor_name ?? "Administración escolar"}</p></div><time className="text-xs text-slate-500" dateTime={row.occurred_at}>{new Date(row.occurred_at).toLocaleString("es-DO", { timeZone: "America/Santo_Domingo" })}</time></article>)}{!data.rows?.length && <p className="p-5 text-slate-500">No hay actividad escolar disponible.</p>}</div></>}
  </>;
}
function activityLabel(action: string, target: string) {
  const labels: Record<string, string> = { student_create: "Estudiante creado y matriculado", student_update: "Información de estudiante actualizada", student_status: "Estado del estudiante actualizado", student_enroll: "Matrícula creada", student_transfer: "Colocación del estudiante actualizada", student_withdraw: "Matrícula retirada", admin_prepare: "Acceso de administrador preparado", admin_complete: "Acceso de administrador completado", admin_status: "Acceso de administrador actualizado", sharing_set: "Compartición con cafetería actualizada", customer_set: "Elegibilidad de estudiante actualizada" };
  return labels[action.replace(/^school_admin_/, "")] ?? ({ students: "Estudiante actualizado", student_enrollments: "Matrícula actualizada", student_campus_placements: "Campus del estudiante actualizado", school_cafeteria_shares: "Compartición actualizada", school_memberships: "Acceso escolar actualizado", invitations: "Acceso preparado actualizado" }[target] ?? "Administración escolar actualizada");
}
