'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { BrandLogo } from './brand-logo';
import { Home,Users,Utensils,ReceiptText,ShieldCheck,LogOut } from './icons';
import type { CafeteriaContext } from '../lib/cafeteria/contracts';
const items=[['','Resumen',Home],['/productos','Productos',Utensils],['/menus','Menús',Utensils],['/personal','Personal POS',Users],['/cajas','Cajas',ReceiptText],['/transacciones','Transacciones',ReceiptText],['/configuracion','Configuración',ShieldCheck]] as const;
export function ConnectedCafeteriaShell({context,cafeteriaId,children}:{context:CafeteriaContext;cafeteriaId:string;children:React.ReactNode}) {
 const path=usePathname(),root='/admin/cafeteria',scope=context.cafeterias.find(c=>c.cafeteria_id===cafeteriaId)!;
 const href=(suffix:string)=>`${root}${suffix}?cafeteria=${cafeteriaId}`;
 const links=(mobile=false)=>items.map(([suffix,label,Icon])=>{const target=root+suffix,current=path===target||(suffix!==''&&path.startsWith(target));return <Link key={target} href={href(suffix)} aria-current={current?'page':undefined} className={mobile?`flex min-h-16 min-w-0 flex-col items-center justify-center gap-1 rounded-xl px-1 text-[10px] font-bold ${current?'bg-teal-50 text-teal-950':'text-slate-600'}`:`nav-link ${current?'bg-white text-pikas-navy':'text-white/80 hover:bg-white/10'}`}><Icon size={18}/><span className={mobile?'max-w-full truncate':undefined}>{label}</span></Link>;});
 return <div className="min-h-screen bg-slate-50 md:grid md:grid-cols-[250px_minmax(0,1fr)]" data-testid="admin-shell"><aside className="sticky top-0 hidden h-screen flex-col bg-teal-950 p-5 text-white md:flex"><Link href={href('')} className="flex min-h-11 items-center"><span className="rounded-xl bg-white p-1"><BrandLogo compact className="size-9"/></span><span className="ml-2 font-black">PIKAS Admin</span></Link><p className="mt-2 text-xs font-bold uppercase tracking-widest text-white/70">Administración de cafetería</p><nav className="mt-8 space-y-1" aria-label="Administración">{links()}</nav><form action="/api/auth/logout" method="post" className="mt-auto"><button className="nav-link w-full text-white/80"><LogOut size={18}/>Cerrar sesión</button></form></aside><div className="min-w-0"><header className="sticky top-0 z-30 flex min-h-14 flex-wrap items-center justify-between gap-3 border-b border-b-teal-200 bg-white/95 px-4 py-3 md:px-6"><div className="min-w-0"><span className="label">Organización</span><p className="truncate text-sm font-bold">{scope.cafeteria_name}</p><p className="text-xs text-slate-500">{scope.account_name} · {context.display_name}</p></div><form method="get"><label className="sr-only" htmlFor="workspace-cafeteria">Cafetería</label><select className="field" name="cafeteria" id="workspace-cafeteria" defaultValue={cafeteriaId}>{context.cafeterias.map(c=><option key={c.cafeteria_id} value={c.cafeteria_id}>{c.cafeteria_name}</option>)}</select><button className="btn-secondary ml-2">Cambiar</button></form><form action="/api/auth/logout" method="post" className="md:hidden"><button aria-label="Cerrar sesión" className="grid size-11 place-items-center rounded-xl text-slate-600"><LogOut size={18}/></button></form></header>{scope.tenant_kind==='sandbox'&&<div className="border-b border-amber-300 bg-amber-100 px-4 py-2 text-sm font-bold text-amber-950" role="status">DEMO / SANDBOX · {scope.cafeteria_name} · Datos de prueba</div>}<main className="app-main mx-auto max-w-7xl p-4 sm:p-5 md:p-6">{children}</main><nav className="mobile-nav fixed inset-x-0 bottom-0 z-40 grid grid-cols-7 border-t bg-white/95 p-1 md:hidden" aria-label="Administración móvil">{links(true)}</nav></div></div>;
}
