"use client";
import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
export type DemoStudent={id:string;firstName:string;lastName:string;preferredName:string;grade:string;code:string;status:"active"|"archived";balance:number;dailyLimit:number;perPurchaseLimit:number;spentToday:number;allergies:string[];blocked:string[]};
export type DemoTx={id:string;studentId:string;description:string;category:string;amount:number;status:"completed"|"pending"|"reversed";createdAt:string};
export type DemoOrder={id:string;studentId:string;item:string;amount:number;status:"submitted"|"confirmed"|"cancelled";createdAt:string};
type State={parent:{name:string;email:string;phone:string};students:DemoStudent[];transactions:DemoTx[];orders:DemoOrder[];budget:{goal:string;limit:number;archived:boolean}};
const initial:State={parent:{name:"Oscar Rosa",email:"familia@demo.pikas.do",phone:"809-555-0142"},students:[{id:"sofia",firstName:"Sofía",lastName:"Rosa",preferredName:"Sofi",grade:"5.º A",code:"PK-10982",status:"active",balance:2450,dailyLimit:350,perPurchaseLimit:250,spentToday:160,allergies:["Maní","Lactosa"],blocked:["Bebidas energéticas"]},{id:"mateo",firstName:"Mateo",lastName:"Rosa",preferredName:"Mateo",grade:"2.º B",code:"PK-11804",status:"active",balance:1680,dailyLimit:300,perPurchaseLimit:200,spentToday:105,allergies:[],blocked:["Bebidas energéticas"]}],transactions:[{id:"tx1",studentId:"sofia",description:"Jugo natural y sándwich",category:"Alimentos",amount:-160,status:"completed",createdAt:"2026-08-11T10:18:00-04:00"},{id:"tx2",studentId:"sofia",description:"Recarga familiar demo",category:"Recarga",amount:1500,status:"completed",createdAt:"2026-08-10T18:45:00-04:00"},{id:"tx3",studentId:"mateo",description:"Agua y barra de cereal",category:"Alimentos",amount:-105,status:"completed",createdAt:"2026-08-11T10:22:00-04:00"}],orders:[{id:"po1",studentId:"sofia",item:"Pasta con pollo",amount:180,status:"confirmed",createdAt:"2026-08-11T08:00:00-04:00"}],budget:{goal:"Meriendas del mes",limit:1200,archived:false}};
type Context={state:State;saveParent:(v:State["parent"])=>void;saveStudent:(v:DemoStudent)=>void;addStudent:(v:Omit<DemoStudent,"id"|"balance"|"spentToday"|"status">)=>void;archive:(id:string,restore?:boolean)=>void;topup:(id:string,amount:number)=>void;preorder:(studentId:string,item:string,amount:number)=>{ok:boolean;message:string};cancelOrder:(id:string)=>void;saveBudget:(goal:string,limit:number)=>void};
const C=createContext<Context|null>(null);const key="pikas:unified-demo:v2";
export function DemoProvider({children}:{children:ReactNode}){const [state,setState]=useState(initial);useEffect(()=>{if(process.env.NEXT_PUBLIC_PIKAS_DEMO_MODE==="true"){const saved=localStorage.getItem(key);if(saved)try{setState(JSON.parse(saved) as State)}catch{localStorage.removeItem(key)}}},[]);const commit=(fn:(s:State)=>State)=>setState(s=>{const n=fn(s);if(process.env.NEXT_PUBLIC_PIKAS_DEMO_MODE==="true")localStorage.setItem(key,JSON.stringify(n));return n});const value=useMemo<Context>(()=>({state,saveParent:parent=>commit(s=>({...s,parent})),saveStudent:student=>commit(s=>({...s,students:s.students.map(x=>x.id===student.id?student:x)})),addStudent:v=>commit(s=>({...s,students:[...s.students,{...v,id:crypto.randomUUID(),balance:0,spentToday:0,status:"active"}]})),archive:(id,restore=false)=>commit(s=>({...s,students:s.students.map(x=>x.id===id?{...x,status:restore?"active":"archived"}:x)})),topup:(id,amount)=>commit(s=>({...s,students:s.students.map(x=>x.id===id?{...x,balance:x.balance+amount}:x),transactions:[{id:crypto.randomUUID(),studentId:id,description:"Recarga familiar de demostración",category:"Recarga",amount,status:"completed",createdAt:new Date().toISOString()},...s.transactions]})),preorder:(studentId,item,amount)=>{const st=state.students.find(x=>x.id===studentId);if(!st)return{ok:false,message:"No encontramos el perfil."};if(st.status!=="active")return{ok:false,message:"Tu cuenta no tiene compras activas."};if(st.balance<amount)return{ok:false,message:"No tienes saldo suficiente."};if(st.spentToday+amount>st.dailyLimit)return{ok:false,message:"Esta compra supera tu límite disponible de hoy."};if(st.blocked.some(x=>item.toLowerCase().includes(x.toLowerCase())))return{ok:false,message:"Tu familia ha bloqueado este producto."};commit(s=>({...s,orders:[{id:crypto.randomUUID(),studentId,item,amount,status:"submitted",createdAt:new Date().toISOString()},...s.orders],students:s.students.map(x=>x.id===studentId?{...x,balance:x.balance-amount,spentToday:x.spentToday+amount}:x),transactions:[{id:crypto.randomUUID(),studentId,description:`Reserva: ${item}`,category:"Preorden",amount:-amount,status:"pending",createdAt:new Date().toISOString()},...s.transactions]}));return{ok:true,message:"Preorden enviada. Puedes seguir su estado aquí."}},cancelOrder:id=>commit(s=>{const o=s.orders.find(x=>x.id===id);if(!o||o.status==="cancelled")return s;return{...s,orders:s.orders.map(x=>x.id===id?{...x,status:"cancelled"}:x),students:s.students.map(x=>x.id===o.studentId?{...x,balance:x.balance+o.amount,spentToday:Math.max(0,x.spentToday-o.amount)}:x),transactions:[{id:crypto.randomUUID(),studentId:o.studentId,description:`Reverso de reserva: ${o.item}`,category:"Reembolso",amount:o.amount,status:"completed",createdAt:new Date().toISOString()},...s.transactions]} }),saveBudget:(goal,limit)=>commit(s=>({...s,budget:{goal,limit,archived:false}}))}),[state]);return <C.Provider value={value}>{children}</C.Provider>}
export function useDemo(){const c=useContext(C);if(!c)throw new Error("DemoProvider ausente");return c}
