"use client";
import {useState} from 'react';
import {type PosPolicy} from '@pikas/data-access';
import {useDemo} from './demo-provider';
export function PosSettings(){
  const {state,savePosPolicy,loadRecommendationScenario,connection}=useDemo();const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<Partial<PosPolicy>>({});
  const groups:Array<{title:string;fields:Array<[keyof PosPolicy,string]>}>=[{title:'Pantalla POS',fields:[['showSales','Mostrar ventas del turno'],['showCount','Mostrar cantidad de transacciones'],['showShiftStart','Mostrar inicio del turno'],['showRegister','Mostrar registro en barra de estado']]},{title:'Permisos de transacción',fields:[['allowCashierRefunds','Permitir reembolsos de caja'],['requireApproval','Requerir aprobación administrativa']]},{title:'Política de reembolso',fields:[['partialRefunds','Permitir reembolsos parciales'],['requireReason','Requerir motivo']]}];
  return <><h1 className="text-3xl font-black">Configuración POS</h1><p className="mt-2">La visibilidad no cambia la recolección de datos. Identidad y estado del sistema siempre visibles.</p>{groups.map(group=><section className="card mt-5 p-5" key={group.title}><h2 className="text-xl font-black">{group.title}</h2>{group.fields.map(([field,label])=><label className="mt-3 flex min-h-12 items-center justify-between gap-4" key={field}><span>{label}</span><input className="size-6" type="checkbox" checked={pending[field]??state.posPolicy[field]} disabled={busy||connection!=='Online'} onChange={async e=>{const checked=e.target.checked;setPending({[field]:checked});setBusy(true);const result=await savePosPolicy({...state.posPolicy,[field]:checked});setNotice(result.ok?'Configuración guardada.':result.message);setPending({});setBusy(false)}}/></label>)}</section>)}<section className="card mt-5 p-5"><h2 className="text-xl font-black">Solicitudes familiares</h2><p>Solicitudes de reembolso de padres: desactivadas. Modelo preparado; revisión y solicitud aún no habilitadas.</p><p className="mt-2">Con aprobación obligatoria, el administrador inicia sesión y procesa el reembolso desde Transacciones. Una solicitud nunca modifica saldos.</p></section><section className="card mt-5 p-5"><h2 className="text-xl font-black">Escenario de demostración</h2><p>Añade 10 productos y compras ficticias de hace 2 y 40 días para mostrar ambos Top 5. No cambia saldo ni gasto de hoy.</p><button className="btn-secondary mt-3" disabled={busy} onClick={async()=>{setBusy(true);const result=await loadRecommendationScenario();setNotice(result.ok?"Historial ficticio cargado.":result.message);setBusy(false)}}>Cargar historial de recomendaciones</button></section>{notice?<p role="status" className="mt-4">{notice}</p>:null}</>;
}
