"use client";

import { useEffect, useState, useTransition } from "react";
import type { PosCartLine, PosMenuItemRecord, PosPurchaseRecord } from "@pikas/data-access";
import { Search, ShieldCheck, LogOut, ReceiptText, Utensils } from "@/components/icons";
import { useDemo } from "@/components/demo-provider";
import { BrandLogo } from "@/components/brand-logo";

const money=(minor:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(minor/100);
const date=(value:string)=>new Intl.DateTimeFormat("es-DO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

function restrictionFor(item:PosMenuItemRecord,allergies:string[],blocked:string[]){
  if(!item.available)return "No disponible en este momento.";
  const allergy=item.allergens.find(value=>allergies.some(student=>student.toLocaleLowerCase("es")===value.toLocaleLowerCase("es")));
  if(allergy)return `No permitido: contiene ${allergy}, una alergia registrada.`;
  if(blocked.some(value=>value.toLocaleLowerCase("es")===item.name.toLocaleLowerCase("es")))return "No permitido: producto bloqueado por la familia.";
  return null;
}

export function PosDashboard({demo}:{demo:boolean}){
  const {state,lookupStudentForPos,checkoutPos}=useDemo();
  const [code,setCode]=useState("");
  const [studentId,setStudentId]=useState<string|null>(null);
  const [lookupError,setLookupError]=useState("");
  const [cart,setCart]=useState<PosCartLine[]>([]);
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("Todos");
  const [confirming,setConfirming]=useState(false);
  const [idempotencyKey,setIdempotencyKey]=useState<string|null>(null);
  const [checkoutError,setCheckoutError]=useState("");
  const [receipt,setReceipt]=useState<PosPurchaseRecord|null>(null);
  const [historyQuery,setHistoryQuery]=useState("");
  const [selectedPurchase,setSelectedPurchase]=useState<PosPurchaseRecord|null>(null);
  const [pending,startTransition]=useTransition();
  const [ready,setReady]=useState(false);
  useEffect(()=>setReady(true),[]);
  if(!demo)return <main className="min-h-screen bg-slate-100"><header className="bg-pikas-navy px-5 py-4 text-white"><strong className="text-xl">PIKAS Cafetería</strong></header><section className="mx-auto mt-8 max-w-2xl rounded-3xl border border-amber-300 bg-white p-7"><span className="chip bg-amber-100 text-amber-950">Configuración requerida</span><h1 className="mt-4 text-3xl font-black">POS de producción no activado</h1><p className="mt-3 text-slate-600">La interfaz no sustituirá datos reales por fixtures. Aplica las migraciones, crea el operador POS y conecta las acciones de producción documentadas antes de usar esta ruta fuera del modo demo.</p><form action="/api/auth/logout" method="post"><button className="btn mt-6 min-h-12"><LogOut size={18}/>Cerrar sesión</button></form></section></main>;
  const student=state.students.find(item=>item.id===studentId)??null;
  const categories=["Todos",...new Set(state.menuItems.map(item=>item.category))];
  const menu=state.menuItems.filter(item=>(category==="Todos"||item.category===category)&&item.name.toLocaleLowerCase("es").includes(query.trim().toLocaleLowerCase("es")));
  const totalMinor=cart.reduce((total,line)=>total+(state.menuItems.find(item=>item.id===line.itemId)?.priceMinor??0)*line.quantity,0);
  const history=state.purchases.filter(item=>`${item.studentName} ${item.items.map(line=>line.name).join(" ")}`.toLocaleLowerCase("es").includes(historyQuery.trim().toLocaleLowerCase("es")));
  const remainingMinor=student?Math.max(0,(student.dailyLimit-student.spentToday)*100):0;
  const partnership=state.administration.partnerships.find(item=>item.id==="partner-active");
  const operator=state.administration.users.find(item=>item.id==="pos-1");

  if(operator?.status!=="active")return <main className="min-h-screen bg-slate-100 p-5"><section className="mx-auto mt-16 max-w-2xl rounded-3xl border border-red-300 bg-white p-7"><span className="chip bg-red-50 text-red-900">Cuenta POS {operator?.status??"inactiva"}</span><h1 className="mt-4 text-3xl font-black">Acceso de caja suspendido</h1><p className="mt-3 text-slate-600">Un administrador de cafetería debe reactivar esta cuenta antes de verificar estudiantes o completar transacciones.</p><form action="/api/auth/logout" method="post"><button className="btn mt-6 min-h-12"><LogOut size={18}/>Cerrar sesión</button></form></section></main>;

  const clearStudent=()=>{setStudentId(null);setCode("");setLookupError("");setCart([]);setCheckoutError("");setReceipt(null);setConfirming(false);setIdempotencyKey(null)};
  const verifyStudent=(submittedCode=code)=>{setLookupError("");setReceipt(null);setCart([]);const result=lookupStudentForPos(submittedCode);if(!result.ok){setStudentId(null);setLookupError(result.reason==="student_inactive"?"Este estudiante no está activo para compras.":"No encontramos un estudiante activo con ese código.");return}setStudentId(result.student.id)};
  const updateQuantity=(itemId:string,quantity:number)=>{setCart(current=>quantity<=0?current.filter(line=>line.itemId!==itemId):current.map(line=>line.itemId===itemId?{...line,quantity}:line));setIdempotencyKey(null);setCheckoutError("")};
  const add=(itemId:string)=>{setCart(current=>{const found=current.find(line=>line.itemId===itemId);return found?current.map(line=>line.itemId===itemId?{...line,quantity:Math.min(20,line.quantity+1)}:line):[...current,{itemId,quantity:1}]});setIdempotencyKey(null);setCheckoutError("");setReceipt(null)};
  const beginCheckout=()=>{if(cart.length===0)return;setIdempotencyKey(crypto.randomUUID());setConfirming(true);setCheckoutError("")};
  const completeCheckout=()=>{if(!student||!idempotencyKey)return;startTransition(()=>{const result=checkoutPos(student.id,cart,idempotencyKey);if(!result.ok){setCheckoutError(result.message);setConfirming(false);return}setReceipt(result.purchase);setCart([]);setConfirming(false);setIdempotencyKey(null)})};

  return <main className="min-h-screen bg-slate-100 pb-12">
    <header className="flex flex-wrap items-center justify-between gap-3 bg-pikas-navy px-4 py-4 text-white md:px-8"><div className="flex items-center gap-3"><span className="rounded-xl bg-white p-1"><BrandLogo compact className="size-9"/></span><div><strong className="text-xl">PIKAS Cafetería</strong><p className="text-xs text-slate-300">Instituto Nueva Generación · Caja 1</p></div></div><div className="flex items-center gap-3"><span className="rounded-full bg-pikas-yellow px-3 py-1 text-xs font-black text-slate-950">{demo?"DEMO LOCAL":"PRODUCCIÓN"}</span><form action="/api/auth/logout" method="post"><button className="flex min-h-11 items-center gap-2 rounded-xl px-3 font-bold hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"><LogOut size={18}/>Salir</button></form></div></header>
    <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
      {demo?<div className="grid gap-3 sm:grid-cols-2"><p className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-950">Modo de demostración: las compras ficticias se guardan en este navegador y se comparten con Familia y Estudiante. No se mueve dinero real.</p><p className={`rounded-2xl border p-4 text-sm font-bold ${partnership?.status==="active"?"border-emerald-300 bg-emerald-50 text-emerald-950":"border-red-300 bg-red-50 text-red-950"}`}><ShieldCheck className="mr-2 inline" size={18}/>Conexión Escuela–Cafetería: {partnership?.status==="active"?"Activa · verificación y transacciones autorizadas":"No activa · verificación bloqueada"}. Alcance mínimo.</p></div>:null}
      <section className="card p-5 md:p-6" aria-labelledby="student-heading"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="label">Paso 1</span><h1 id="student-heading" className="mt-2 text-3xl font-black">Validar estudiante</h1></div>{student?<button className="btn-secondary min-h-11" onClick={clearStudent}>Cambiar estudiante</button>:null}</div>
        {!student?<form className="mt-5 max-w-xl" onSubmit={event=>{event.preventDefault();verifyStudent(String(new FormData(event.currentTarget).get("studentCode")??""))}}><label className="font-bold" htmlFor="student-code">Código estudiantil</label><div className="relative mt-2"><Search className="absolute left-4 top-3.5 text-slate-400" size={20}/><input id="student-code" name="studentCode" value={code} onChange={event=>setCode(event.target.value.toUpperCase())} className="field pl-12 uppercase" placeholder="Ej. PK-10982" autoComplete="off" aria-describedby={lookupError?"lookup-error":"student-code-help"} required pattern="PK-[0-9]{5}"/><span id="student-code-help" className="mt-2 block text-xs text-slate-500">Introduce el código completo con el formato PK-00000.</span></div><button type="button" onClick={event=>verifyStudent(String(new FormData(event.currentTarget.form!).get("studentCode")??""))} disabled={!ready} className="btn mt-4 min-h-12 w-full disabled:opacity-60 sm:w-auto">{ready?"Comprobar estudiante":"Preparando verificación…"}</button>{lookupError?<p id="lookup-error" role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">{lookupError}</p>:null}</form>:<div className="mt-5 grid gap-4 lg:grid-cols-[auto_1fr] lg:items-center"><span aria-hidden="true" className="grid size-20 place-items-center rounded-3xl bg-blue-100 text-2xl font-black text-blue-900">{student.firstName[0]}{student.lastName[0]}</span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-black">{student.preferredName}</h2><span className="chip bg-emerald-50 text-emerald-800">Activo</span></div><p className="text-sm text-slate-600">Instituto Nueva Generación · {student.grade}</p><dl className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">Saldo disponible</dt><dd className="text-lg font-black">{money(student.balance*100)}</dd></div><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">Disponible hoy</dt><dd className="text-lg font-black">{money(remainingMinor)}</dd></div><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">Límite por compra</dt><dd className="text-lg font-black">{money(student.perPurchaseLimit*100)}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{student.allergies.map(value=><span key={value} className="chip bg-red-50 text-red-900">Alergia: {value}</span>)}{student.blocked.map(value=><span key={value} className="chip bg-amber-50 text-amber-950">Bloqueado: {value}</span>)}{student.allergies.length===0&&student.blocked.length===0?<span className="text-sm text-slate-500">Sin alertas alimentarias registradas.</span>:null}</div></div></div>}
      </section>

      {student?<div className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><section className="card p-5 md:p-6" aria-labelledby="menu-heading"><span className="label">Paso 2</span><h2 id="menu-heading" className="mt-2 text-2xl font-black">Menú disponible</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="sr-only" htmlFor="menu-search">Buscar en el menú</label><input id="menu-search" className="field" placeholder="Buscar producto" value={query} onChange={event=>setQuery(event.target.value)}/><div className="flex gap-2 overflow-auto" aria-label="Filtrar por categoría">{categories.map(value=><button key={value} onClick={()=>setCategory(value)} className={`chip min-h-11 whitespace-nowrap ${category===value?"bg-slate-950 text-white":"bg-slate-100 text-slate-800"}`} aria-pressed={category===value}>{value}</button>)}</div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{menu.map(item=>{const restriction=restrictionFor(item,student.allergies,student.blocked);return <article className="rounded-2xl border bg-white p-4" key={item.id}><div className="flex justify-between gap-3"><div><h3 className="font-black">{item.name}</h3><p className="text-sm text-slate-500">{item.category} · {item.description}</p></div><strong>{money(item.priceMinor)}</strong></div>{item.allergens.length?<p className="mt-3 text-xs font-bold text-slate-600">Contiene: {item.allergens.join(", ")}</p>:null}{restriction?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-950">{restriction}</p>:null}<button disabled={Boolean(restriction)} onClick={()=>add(item.id)} className="btn mt-4 min-h-11 w-full disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-600">{restriction?"No se puede añadir":"Añadir al carrito"}</button></article>})}</div>{menu.length===0?<p className="mt-5 rounded-xl bg-slate-50 p-5 text-center text-slate-600">No hay productos que coincidan con la búsqueda.</p>:null}</section>
        <aside className="card h-fit p-5 md:p-6" aria-labelledby="cart-heading"><span className="label">Paso 3</span><h2 id="cart-heading" className="mt-2 text-2xl font-black">Carrito</h2>{checkoutError?<p role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">{checkoutError}</p>:null}{cart.length===0?<div className="mt-5 rounded-2xl bg-slate-50 p-6 text-center"><Utensils className="mx-auto text-slate-400"/><p className="mt-2 font-bold">El carrito está vacío</p><p className="text-sm text-slate-500">Añade un producto permitido para continuar.</p></div>:<div className="mt-4 divide-y">{cart.map(line=>{const item=state.menuItems.find(candidate=>candidate.id===line.itemId);if(!item)return null;return <div className="py-4" key={line.itemId}><div className="flex justify-between gap-2"><strong>{item.name}</strong><strong>{money(item.priceMinor*line.quantity)}</strong></div><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2" aria-label={`Cantidad de ${item.name}`}><button className="btn-secondary min-h-11 min-w-11" aria-label={`Reducir ${item.name}`} onClick={()=>updateQuantity(line.itemId,line.quantity-1)}>−</button><span className="min-w-8 text-center font-black" aria-live="polite">{line.quantity}</span><button className="btn-secondary min-h-11 min-w-11" aria-label={`Aumentar ${item.name}`} onClick={()=>updateQuantity(line.itemId,line.quantity+1)}>+</button></div><button className="min-h-11 font-bold text-red-700 underline" onClick={()=>updateQuantity(line.itemId,0)}>Quitar</button></div></div>})}<div className="flex justify-between py-5 text-xl font-black"><span>Total</span><span>{money(totalMinor)}</span></div><button className="btn min-h-12 w-full" onClick={beginCheckout}>Revisar y confirmar</button><button className="btn-secondary mt-2 min-h-11 w-full" onClick={()=>{setCart([]);setCheckoutError("");setIdempotencyKey(null)}}>Vaciar carrito</button></div>}</aside></div>:null}

      {receipt?<section role="status" className="rounded-3xl border border-emerald-300 bg-emerald-50 p-6" aria-labelledby="receipt-heading"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-emerald-800"/><div><h2 id="receipt-heading" className="text-2xl font-black text-emerald-950">Compra completada</h2><p className="mt-1 text-emerald-900">Recibo {receipt.id.slice(0,8)} · {receipt.studentName} · {money(receipt.totalMinor)}</p><p className="mt-2 text-sm text-emerald-900">El saldo y el movimiento ya están disponibles en Cafetería, Estudiante y Familia dentro de este demo.</p></div></div></section>:null}

      <section className="card p-5 md:p-6" aria-labelledby="history-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="label">Actividad de caja</span><h2 id="history-heading" className="mt-2 text-2xl font-black">Historial POS</h2></div><label className="w-full sm:w-72"><span className="sr-only">Buscar transacciones</span><input className="field" placeholder="Buscar estudiante o producto" value={historyQuery} onChange={event=>setHistoryQuery(event.target.value)}/></label></div>{history.length===0?<div className="mt-5 rounded-2xl bg-slate-50 p-7 text-center"><ReceiptText className="mx-auto text-slate-400"/><p className="mt-2 font-bold">Aún no hay compras POS</p><p className="text-sm text-slate-500">Las compras completadas en este navegador aparecerán aquí.</p></div>:<div className="mt-4 divide-y">{history.map(purchase=><button key={purchase.id} onClick={()=>setSelectedPurchase(purchase)} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-700"><div><strong className="block">{purchase.studentName}</strong><span className="text-sm text-slate-500">{purchase.items.map(item=>`${item.quantity}× ${item.name}`).join(", ")} · {date(purchase.createdAt)}</span></div><div className="text-right"><strong>{money(purchase.totalMinor)}</strong><span className="block text-xs font-bold text-emerald-700">Completada</span></div></button>)}</div>}</section>
    </div>

    {confirming&&student?<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/60 sm:place-items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="confirm-heading" className="w-full max-w-lg rounded-t-3xl bg-white p-6 sm:rounded-3xl"><h2 id="confirm-heading" className="text-2xl font-black">Confirmar compra</h2><p className="mt-2 text-slate-600">Se cargarán {money(totalMinor)} a la billetera de {student.preferredName}. Esta acción crea un movimiento completado.</p><ul className="mt-4 space-y-2">{cart.map(line=>{const item=state.menuItems.find(candidate=>candidate.id===line.itemId);return item?<li className="flex justify-between" key={line.itemId}><span>{line.quantity}× {item.name}</span><strong>{money(item.priceMinor*line.quantity)}</strong></li>:null})}</ul><div className="mt-6 flex gap-2"><button disabled={pending} className="btn-secondary min-h-12 flex-1" onClick={()=>setConfirming(false)}>Volver</button><button disabled={pending} className="btn min-h-12 flex-1 disabled:opacity-60" onClick={completeCheckout}>{pending?"Procesando…":"Completar compra"}</button></div></div></div>:null}
    {selectedPurchase?<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/60 sm:place-items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="detail-heading" className="w-full max-w-lg rounded-t-3xl bg-white p-6 sm:rounded-3xl"><h2 id="detail-heading" className="text-2xl font-black">Detalle de transacción</h2><p className="mt-2 text-sm text-slate-500">{date(selectedPurchase.createdAt)} · {selectedPurchase.employeeLabel}</p><p className="mt-4 font-bold">Estudiante: {selectedPurchase.studentName}</p><ul className="mt-4 divide-y">{selectedPurchase.items.map(item=><li key={item.itemId} className="flex justify-between py-3"><span>{item.quantity}× {item.name}</span><strong>{money(item.unitPriceMinor*item.quantity)}</strong></li>)}</ul><div className="flex justify-between border-t pt-4 text-xl font-black"><span>Total</span><span>{money(selectedPurchase.totalMinor)}</span></div><p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">Reversos y reembolsos requieren autorización de gerencia y no están disponibles en este milestone.</p><button className="btn mt-5 min-h-12 w-full" onClick={()=>setSelectedPurchase(null)}>Cerrar detalle</button></div></div>:null}
  </main>;
}
