-- PIKAS unified schema. Monetary values are integer minor units (DOP centavos).
create extension if not exists pgcrypto;
create type public.user_role as enum ('parent','student','pos','admin');
create type public.record_status as enum ('active','archived');
create type public.preorder_status as enum ('draft','submitted','confirmed','preparing','ready','completed','cancelled','declined');
create type public.ledger_direction as enum ('credit','debit');

create table public.schools(id uuid primary key default gen_random_uuid(),name text not null,status record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role user_role not null,school_id uuid references public.schools,full_name text not null,email text,phone text,avatar_url text,preferred_language text not null default 'es',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.families(id uuid primary key default gen_random_uuid(),family_code text not null unique,display_name text not null,status record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.family_members(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families,profile_id uuid not null references public.profiles,relationship text not null,can_manage_students boolean not null default false,can_manage_finances boolean not null default false,unique(family_id,profile_id));
create table public.students(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families,school_id uuid not null references public.schools,profile_id uuid unique references public.profiles,student_code text not null unique,first_name text not null,last_name text not null,preferred_name text,grade text not null,avatar_url text,status record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.wallets(id uuid primary key default gen_random_uuid(),student_id uuid not null unique references public.students,status record_status not null default 'active',currency char(3) not null default 'DOP',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.wallet_ledger_entries(id uuid primary key default gen_random_uuid(),wallet_id uuid not null references public.wallets,transaction_type text not null,amount_minor bigint not null check(amount_minor>0),direction ledger_direction not null,status text not null check(status in ('pending','completed','declined','reversed')),description text not null,category text not null,external_reference text,related_entry_id uuid references public.wallet_ledger_entries,idempotency_key text not null unique,created_by uuid references public.profiles,created_at timestamptz not null default now());
create index ledger_wallet_created_idx on public.wallet_ledger_entries(wallet_id,created_at desc);
create view public.wallet_balances with (security_invoker=true) as select wallet_id,coalesce(sum(case when direction='credit' then amount_minor else -amount_minor end) filter(where status='completed'),0)::bigint as balance_minor from public.wallet_ledger_entries group by wallet_id;
create table public.student_controls(student_id uuid primary key references public.students,daily_spending_limit_minor bigint not null default 0 check(daily_spending_limit_minor>=0),per_transaction_limit_minor bigint not null default 0 check(per_transaction_limit_minor>=0),transfers_allowed boolean not null default false,parental_approval_threshold_minor bigint not null default 0,external_purchases_allowed boolean not null default false,notifications_enabled boolean not null default true,updated_by uuid references public.profiles,updated_at timestamptz not null default now());
create table public.allergies(id uuid primary key default gen_random_uuid(),name text not null unique);
create table public.student_allergies(student_id uuid references public.students,allergy_id uuid references public.allergies,created_by uuid references public.profiles,primary key(student_id,allergy_id));
create table public.blocked_products(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students,product_name text not null,created_by uuid references public.profiles,created_at timestamptz not null default now());
create table public.menu_items(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools,name text not null,description text not null default '',category text not null,price_minor bigint not null check(price_minor>=0),image_url text,allergen_ids uuid[] not null default '{}',available boolean not null default true,created_at timestamptz not null default now());
create table public.preorders(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students,status preorder_status not null default 'draft',total_minor bigint not null default 0,pickup_at timestamptz,reservation_entry_id uuid references public.wallet_ledger_entries,idempotency_key text not null unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.preorder_items(id uuid primary key default gen_random_uuid(),preorder_id uuid not null references public.preorders on delete cascade,menu_item_id uuid not null references public.menu_items,quantity integer not null check(quantity>0),unit_price_minor bigint not null check(unit_price_minor>=0));
create table public.budgets(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students,period text not null check(period in ('weekly','monthly')),goal text not null,limit_minor bigint not null check(limit_minor>0),status record_status not null default 'active',starts_on date not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles,type text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());

create or replace function public.current_role() returns user_role language sql stable security definer set search_path=public as $$select role from profiles where id=auth.uid()$$;
create or replace function public.can_access_student(target uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from students s left join family_members fm on fm.family_id=s.family_id where s.id=target and (s.profile_id=auth.uid() or fm.profile_id=auth.uid() or public.current_role()='admin' or (public.current_role()='pos' and s.school_id=(select school_id from profiles where id=auth.uid()))))$$;
alter table public.profiles enable row level security;alter table public.families enable row level security;alter table public.family_members enable row level security;alter table public.students enable row level security;alter table public.wallets enable row level security;alter table public.wallet_ledger_entries enable row level security;alter table public.student_controls enable row level security;alter table public.allergies enable row level security;alter table public.student_allergies enable row level security;alter table public.blocked_products enable row level security;alter table public.menu_items enable row level security;alter table public.preorders enable row level security;alter table public.preorder_items enable row level security;alter table public.budgets enable row level security;alter table public.notifications enable row level security;
create policy profiles_select_self on public.profiles for select using(id=auth.uid() or public.current_role()='admin');
create policy profiles_update_self on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy family_members_select_linked on public.family_members for select using(profile_id=auth.uid() or public.current_role()='admin');
create policy families_select_linked on public.families for select using(public.current_role()='admin' or exists(select 1 from family_members fm where fm.family_id=id and fm.profile_id=auth.uid()));
create policy students_select_scoped on public.students for select using(can_access_student(id));
create policy students_parent_insert on public.students for insert with check(public.current_role()='parent' and exists(select 1 from family_members fm where fm.family_id=family_id and fm.profile_id=auth.uid() and fm.can_manage_students));
create policy students_parent_update on public.students for update using(public.current_role()='parent' and can_access_student(id)) with check(public.current_role()='parent' and can_access_student(id));
create policy wallets_select_scoped on public.wallets for select using(can_access_student(student_id));
create policy ledger_select_scoped on public.wallet_ledger_entries for select using(exists(select 1 from wallets w where w.id=wallet_id and can_access_student(w.student_id)));
-- No UPDATE or DELETE ledger policy: completed financial history is immutable to clients.
create policy controls_select_scoped on public.student_controls for select using(can_access_student(student_id));
create policy controls_parent_update on public.student_controls for update using(public.current_role() in ('parent','admin') and can_access_student(student_id)) with check(public.current_role() in ('parent','admin') and can_access_student(student_id));
create policy allergies_authenticated_read on public.allergies for select to authenticated using(true);
create policy student_allergies_scoped_read on public.student_allergies for select using(can_access_student(student_id));
create policy blocked_products_scoped_read on public.blocked_products for select using(can_access_student(student_id));
create policy menu_school_read on public.menu_items for select to authenticated using(available and school_id=(select school_id from profiles where id=auth.uid()) or public.current_role()='admin');
create policy preorders_scoped_read on public.preorders for select using(can_access_student(student_id));
create policy budgets_student_read on public.budgets for select using(can_access_student(student_id));
create policy budgets_student_write on public.budgets for all using(student_id=(select id from students where profile_id=auth.uid())) with check(student_id=(select id from students where profile_id=auth.uid()));
create policy notifications_owner on public.notifications for select using(profile_id=auth.uid());

-- Privileged RPC performs all checks server-side and reserves funds atomically.
create or replace function public.create_preorder(p_student_id uuid,p_item_id uuid,p_quantity integer,p_idempotency_key text) returns uuid language plpgsql security definer set search_path=public as $$declare v_item menu_items;v_wallet wallets;v_controls student_controls;v_total bigint;v_balance bigint;v_order uuid;begin if not can_access_student(p_student_id) then raise exception 'not_authorized';end if;select * into v_item from menu_items where id=p_item_id and available;select * into v_wallet from wallets where student_id=p_student_id and status='active';select * into v_controls from student_controls where student_id=p_student_id;v_total:=v_item.price_minor*p_quantity;if v_total>v_controls.per_transaction_limit_minor then raise exception 'per_transaction_limit';end if;select coalesce(balance_minor,0) into v_balance from wallet_balances where wallet_id=v_wallet.id;if v_balance<v_total then raise exception 'insufficient_funds';end if;insert into preorders(student_id,status,total_minor,idempotency_key) values(p_student_id,'submitted',v_total,p_idempotency_key) returning id into v_order;insert into preorder_items(preorder_id,menu_item_id,quantity,unit_price_minor) values(v_order,p_item_id,p_quantity,v_item.price_minor);insert into wallet_ledger_entries(wallet_id,transaction_type,amount_minor,direction,status,description,category,idempotency_key,created_by) values(v_wallet.id,'funds_reservation',v_total,'debit','completed','Reserva de preorden','Preorden',p_idempotency_key||':reservation',auth.uid());return v_order;end$$;
